(function(){
'use strict';
const root=new URL('../',document.currentScript.src),url=p=>new URL(p,root).href;
const style=document.createElement('style');style.textContent='.ap{position:fixed;inset:38px 0 0;z-index:100;background:#f7f9fc;color:#142337;display:flex;flex-direction:column;font-family:Arial,sans-serif}.ap[hidden]{display:none}.ap *{box-sizing:border-box}.ap header,.ap footer{background:white;padding:10px 15px;display:flex;gap:10px;align-items:center;border-bottom:1px solid #d9e1ec}.ap footer{border-top:1px solid #d9e1ec}.ap h2{font-size:18px;flex:1;margin:0}.ap main{flex:1;overflow:auto;padding:20px}.ap article{max-width:1120px;margin:auto}.ap h3{font-size:24px;color:#0039a6;margin:0 0 15px}.ap p{line-height:1.6}.ap button,.ap select,.ap input{font:inherit}.ap button{background:white;color:#0039a6;border:1px solid #b7c9e8;border-radius:9px;padding:11px 15px;cursor:pointer;font-weight:bold}.ap .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ap .grid button{font-size:20px;text-align:left;min-height:75px}.ap .grid small{display:block;font-size:14px;font-weight:normal;margin-top:8px}.ap .text{background:#fff;border:1px solid #d9e1ec;border-radius:12px;padding:22px;font-size:23px;line-height:1.7;margin-bottom:15px}.ap .text input{width:185px;padding:7px;border:1px solid #9eb4d1;border-radius:7px;color:#142337}.ap .text small{font-size:14px;color:#0039a6;font-weight:bold}.ap .keys{background:#edf3ff;padding:17px;font-size:18px;line-height:1.65;margin-top:15px;border-radius:10px}.ap .keys[hidden]{display:none}.ap .feedback{font-size:18px;line-height:1.5;margin:15px 0}.ap .actions{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.ap .ok{background:#edf9f1!important;border-color:#26724d!important}.ap .bad{background:#fff0ee!important;border-color:#bf322a!important}.ap select{padding:10px;max-width:100%;background:white;border:1px solid #b7c9e8;border-radius:8px}.ap audio{width:100%;margin:15px 0}.ap a{color:#0039a6}.ap footer span{flex:1;text-align:center;font-size:14px}.ap .muted{color:#53657a;font-size:14px}.ap :focus-visible{outline:3px solid #76a9f5;outline-offset:2px}@media(max-width:650px){.ap main{padding:12px}.ap h2{font-size:14px}.ap header{padding:8px;gap:5px}.ap .grid{grid-template-columns:1fr}.ap .text{font-size:19px;padding:15px}.ap .text input{width:145px}.ap button{padding:9px}}';document.head.append(style);
const labels=['Past detective · 5 мин','Meaning → form · 8 мин','ЕГЭ 19–24 · 14 мин','Reading · 10 мин','Repair clinic · 7 мин','Interview · 10 мин','Exit test · 6 мин','Домашняя работа'];
const warm=[
['Last Saturday I visited my grandparents.',0,'Завершённое событие: visited.'],
['At eight yesterday evening I was doing my homework.',1,'Процесс в конкретный момент: was doing.'],
['When I reached the platform, the train had already left.',2,'Сначала поезд ушёл, потом я пришёл.'],
['She had been practising for two hours when her teacher arrived.',3,'Длительность до прошлого момента.'],
['I dropped my phone while I was getting off the bus. Назови время was getting.',1,'Фоновый процесс; dropped — короткое событие.'],
['We had never seen snow before we moved to Canada.',2,'Опыт до переезда.']];
const contrast=[
['At 7 p.m. yesterday, Leo ___ dinner. He was still in the kitchen when I called.',['cooked','was cooking','had cooked','had been cooking'],[1],'Процесс в 19:00 → was cooking.'],
['By the time I got home, my brother ___ all the sandwiches. There were none left.',['ate','was eating','had eaten','had been eating'],[2],'Результат до возвращения → had eaten.'],
['By six yesterday, she ___ ten kilometres.',['ran','was running','had run','had been running'],[2],'Завершённое количество к прошлому сроку → had run.'],
['She ___ for an hour when she finally stopped to rest.',['ran','was running','had run','had been running'],[3,2],'Ожидаем had been running: акцент на длительности. Had run for an hour тоже грамматически допустимо.'],
['I ___ the answer immediately, so I put my hand up.',['knew','was knowing','had known','had been knowing'],[0],'Know — состояние. Здесь Past Simple.'],
['I ___ my keys yesterday, but I found them under the sofa later.',['lost','was losing','had lost','had been losing'],[0],'Цепочка завершённых событий.'],
['While we ___ across the square, it started to rain.',['walked','were walking','had walked','had been walking'],[1],'Фоновый процесс + короткое событие.'],
['By six o’clock yesterday, the students ___ the whole test.',['finished','were finishing','had finished','had been finishing'],[2],'Результат к прошлому моменту.']];
const sets=[
{title:'Set A · A difficult morning',lines:[
['Yesterday, Emma ___ home at eight o’clock.','LEAVE',['left'],'Завершённое событие вчера.'],
['She ___ towards the bus stop when she realised that her travel card was missing.','WALK',['was walking'],'Процесс, во время которого она заметила проблему.'],
['By that moment, she ___ the card at home, so she had to go back.','FORGET',['had forgotten'],'Забыла раньше, чем обнаружила пропажу.'],
['She ___ at the stop for twenty minutes when a bus finally arrived.','WAIT',['had been waiting','had waited'],'Длительность до прибытия автобуса.'],
['On the bus, she ___ a classmate.','MEET',['met'],'Следующее событие рассказа.'],
['He ___ her that their first lesson had been cancelled.','TELL',['told'],'Завершённое событие.']]},
{title:'Set B · The school video',lines:[
['At five o’clock yesterday, Ben and his friends ___ their school video on a laptop.','WATCH',['were watching'],'Процесс в конкретный момент.'],
['Suddenly, the lights ___ out.','GO',['went'],'Внезапное событие.'],
['By then, Ben ___ the laptop battery completely, so the video kept playing.','CHARGE',['had charged'],'Результат к тому моменту.'],
['Luckily, they ___ any electricity to finish watching it.','NOT NEED',['did not need',"didn't need"],'did not + начальная форма.'],
['Ben ___ the film for two hours without a break when his friends arrived earlier that afternoon.','EDIT',['had been editing','had edited'],'Длительность до прихода друзей.'],
['After the final scene, everyone ___ the ending funny.','FIND',['found'],'Find в значении «считать»: оценка в прошлом.']]}
];
const exit={title:'Exit test · A lost notebook',lines:[
['Yesterday, Anna ___ to school early.','COME',['came'],'Завершённое событие.'],
['At 8:15, she ___ for her notebook in the classroom.','LOOK',['was looking'],'Процесс в 8:15.'],
['By that time, the cleaner ___ it to the school office.','TAKE',['had taken'],'Перенесли до того момента.'],
['Anna ___ for ten minutes when a teacher offered to help.','SEARCH',['had been searching','had searched'],'Длительность до предложения помощи.'],
['She ___ where her notebook was.','NOT KNOW',['did not know',"didn't know"],'did not + know; не was knowing.'],
['In the end, the secretary ___ it to her.','GIVE',['gave'],'Завершённое событие.']]};
const headings=['A practical place to study','A useful mistake','A new role in a group','An unexpected source of help','A deadline that changed a habit','A different way to remember','A journey to another country'];
const texts=[
['Before her last school year, Mia had revised mainly on the night before a test. She often received reasonable marks, but a week later she could remember very little. In September, she changed her routine. She began using short question cards on several different days. Instead of reading her notes again and again, she tried to recall the information without looking. The new method took less time and helped her remember more.',5],
['Leo was preparing a history presentation when his younger sister came into his room. He asked her to leave, but she wanted to know what he was doing. As he explained the topic, he noticed that he could not answer one of her simple questions. He checked his sources and corrected the presentation. Later, he realised that explaining the subject to someone much younger had helped him understand it better.',3],
['When Sara began secondary school, she usually did her homework in bed. Messages kept arriving on her phone, and she found it difficult to concentrate. One afternoon, she tried the local library. There was enough space for her books, and the quiet room made a difference. She left her phone in her bag and completed her work before dinner. After that, she returned to the same table twice a week.',0],
['In his first group project, Amir had stayed quiet while the other students made the decisions. Their presentation was confusing because nobody had checked how the different parts fitted together. For the next project, he suggested a short meeting before they started. He wrote down everyone’s responsibilities and checked their progress. He did not do all the work himself, but he helped the group work together more effectively.',2],
['Ellie thought she understood the grammar, but her practice test showed a different picture. She had chosen several answers just because she recognised a time expression. Her teacher asked her to draw the events on a timeline. Ellie discovered that some actions had happened before the main story began. She rewrote the sentences and explained each choice aloud. The disappointing result showed her exactly what she needed to practise.',1],
['Daniel used to leave every assignment until the last evening. One week, he had to hand in three projects on the same day. He stayed up late and still failed to finish one of them. Afterwards, he put the next deadlines on a calendar and divided each project into smaller steps. By the end of the following month, he had completed every assignment on time and no longer worked through the night.',4]];
const errors=[
['Yesterday she has gone to the library.','went','Yesterday she went to the library.','Yesterday → завершённый прошлый период.'],
['At 8 p.m. I did my homework when the lights went out.','was doing','At 8 p.m. I was doing my homework when the lights went out.','Процесс + прерывающее событие.'],
['By the time we arrived, the film already started.','had already started','By the time we arrived, the film had already started.','Фильм начался раньше.'],
['She had been wrote for two hours before she took a break.','had been writing','She had been writing for two hours before she took a break.','had + been + V-ing.'],
['He didn’t knew the answer.','know','He didn’t know the answer.','После didn’t — начальная форма.'],
['I was knowing her at school.','knew','I knew her at school.','Know — состояние.']];
let box,stage=-1,item=0,values={},clock;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const norm=s=>s.toLowerCase().replace(/’/g,"'").replace(/\s+/g,' ').trim();
function button(t,f){const b=document.createElement('button');b.type='button';b.textContent=t;b.onclick=f;return b;}
function save(){box.querySelectorAll('[data-save]').forEach(e=>values[e.dataset.save]=e.value);}
function stop(){clearInterval(clock);box.querySelectorAll('audio').forEach(a=>a.pause());}
function go(s,i=0){save();stop();stage=s;item=i;render();}
function keys(host,html){const k=document.createElement('div');k.className='keys';k.hidden=true;k.innerHTML=html;host.append(button('Показать ответы',()=>{k.hidden=!k.hidden;}),k);}
function nav(n=1){const f=document.createElement('footer');f.append(button('← Назад',()=>item?go(stage,item-1):go(stage-1)));const count=document.createElement('span');count.textContent=labels[stage]+(n>1?' · '+(item+1)+' / '+n:'');f.append(count,button(item<n-1?'Следующее →':'Следующий блок →',()=>item<n-1?go(stage,item+1):go(stage<7?stage+1:-1)));box.append(f);}
window.openArinaPastToday=function(){if(!box){box=document.createElement('section');box.className='ap';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','Week 2 Lesson 3 · Past');document.body.append(box);}stage=-1;item=0;box.hidden=false;document.body.style.overflow='hidden';render();};
function render(){box.innerHTML='';const header=document.createElement('header');header.append(button('К уроку',()=>go(-1)));const title=document.createElement('h2');title.textContent='3 октября · Week 2 · Lesson 3 · PAST';header.append(title,button('Закрыть',()=>{save();stop();box.hidden=true;document.body.style.overflow='';}));box.append(header);const main=document.createElement('main');main.innerHTML='<article></article>';box.append(main);const h=main.firstChild;
if(stage<0){h.innerHTML='<h3>Past tenses · 60 минут</h3><p>Факт → процесс → более раннее событие → длительность до прошлого момента.</p><div class="grid"></div><p class="muted">Авторская тренировка в формате ЕГЭ. Аудио — из вашего пособия Expert. Ответы открываются по кнопке. Полный банк Expert вводим по одной теме, отдельно от грамматического плана.</p>';const g=h.querySelector('.grid');labels.forEach((l,s)=>{const b=button(l,()=>go(s));const small=document.createElement('small');small.textContent=['6 быстрых контекстов','8 контекстов: смысл и форма','Два связных текста · 12 преобразований','6 текстов · 7 заголовков','6 ошибок · исправь форму','Education · исходная запись + Past follow-up','6 новых заданий без подсказок','Past forms и irregular verbs'][s];b.append(small);g.append(b);});return;}
if(stage===0||stage===1){const q=(stage===0?warm:contrast)[item],opts=stage===0?['Past Simple','Past Continuous','Past Perfect','Past Perfect Continuous']:q[1],accepted=stage===0?[q[1]]:q[2],why=stage===0?q[2]:q[3];h.innerHTML='<h3>'+labels[stage]+'</h3><p class="muted">Выбери время или форму. Объясни смысл: что случилось сначала и что было в процессе.</p><div class="text">'+esc(q[0])+'</div><div class="grid"></div><div class="feedback" role="status"></div>';opts.forEach((o,j)=>h.querySelector('.grid').append(button(o,function(){h.querySelectorAll('.grid button').forEach(b=>b.classList.remove('ok','bad'));this.classList.add(accepted.includes(j)?'ok':'bad');h.querySelector('.feedback').textContent=(accepted.includes(j)?'Допустимо. ':'Проверь смысл. ')+why;})));if(stage===1&&item===0)keys(h,'<b>Past Simple:</b> V2 / did not + V — факт или цепочка событий.<br><b>Past Continuous:</b> was/were + V-ing — процесс в прошлом.<br><b>Past Perfect:</b> had + V3 — результат до другого прошлого момента.<br><b>Past Perfect Continuous:</b> had been + V-ing — длительность до прошлого момента.<br>Маркер — подсказка, не правило. Past Perfect не обязателен после каждого before/after. Perfect Simple тоже может выражать длительность; Continuous подчёркивает процесс.');nav(stage===0?6:8);return;}
if(stage===2||stage===6){gap(h,stage===2?sets[item]:exit,'set'+stage+'-'+item);nav(stage===2?2:1);return;}
if(stage===3){const q=texts[item],id='read'+item;h.innerHTML='<h3>Reading · Text '+String.fromCharCode(65+item)+'</h3><p class="muted">Выбери заголовок. Каждый используется один раз; один лишний. Найди пример Past и объясни выбор формы.</p><div class="text">'+q[0]+'</div><select aria-label="Заголовок" data-save="'+id+'"><option value="">Выбери заголовок</option>'+headings.map((x,j)=>'<option value="'+j+'">'+(j+1)+'. '+x+'</option>').join('')+'</select><div class="feedback" role="status"></div>';const s=h.querySelector('select');s.value=values[id]||'';h.append(button('Проверить',()=>{save();h.querySelector('.feedback').textContent=s.value===''?'Выбери заголовок.':Number(s.value)===q[1]?'Верно. Докажи выбор фразой из текста.':'Вернись к главной мысли текста.';}));keys(h,'A–6 · B–4 · C–1 · D–3 · E–2 · F–5. Лишний: 7.<br>Доказательства: recall without looking; younger sister’s question; quiet library; organising the group; learning from errors; planning around deadlines.');nav(6);return;}
if(stage===4){const q=errors[item],id='error'+item;h.innerHTML='<h3>Repair clinic</h3><p class="muted">Замени ошибочную форму. Введи только исправление, затем прочитай предложение.</p><div class="text">'+q[0]+'</div><input aria-label="Исправленная форма" data-save="'+id+'" value="'+esc(values[id]||'')+'"><div class="feedback" role="status"></div>';h.append(button('Проверить',()=>{save();h.querySelector('.feedback').textContent=norm(values[id]||'')===q[1]?'Верно. '+q[3]:'Ожидаемая форма: '+q[1]+'. '+q[3];}));keys(h,esc(q[2])+'<br>'+q[3]);nav(6);return;}
if(stage===5){h.innerHTML='<h3>Education · Interview 1</h3><p>Answer five questions. Give full answers: 2–3 sentences. You have 40 seconds to answer each question.</p><audio controls preload="metadata" aria-label="Education interview" src="'+url('expert/audio/13.mp3')+'"></audio><p class="muted">Первый проход — с паузами исходной записи. Затем повторите два ответа и выполните дополнительную практику Past.</p><div class="actions"><button data-timer>40 секунд</button><span role="status" data-clock>00:40</span></div><div class="actions"><a href="'+url('expert/pdf/expert-07.pdf')+'#page=3" target="_blank" rel="noopener">Скрипт из пособия</a><a href="'+url('expert/pdf/expert-07.pdf')+'#page=4" target="_blank" rel="noopener">Модели ответов</a></div><div class="text"><b>Past follow-up после аудио</b><br>1. What did you do after school yesterday?<br>2. What were you doing at eight last night?<br>3. Had you finished your homework before you went to bed?<br>4. How long had you been studying before you took your last break?</div>';h.querySelector('[data-timer]').onclick=()=>{clearInterval(clock);let n=40;const el=h.querySelector('[data-clock]');el.textContent='00:40';clock=setInterval(()=>{n--;el.textContent='00:'+String(n).padStart(2,'0');if(n===0)clearInterval(clock);},1000);};keys(h,'<b>Чек-лист:</b> прямой ответ · 2–3 полных предложения · подходящее время · конкретная подробность.<br><b>Пример follow-up:</b> Yesterday, I revised English after school. I was working on a grammar test when my friend called. By nine, I had finished all the exercises. I had been studying for an hour, so I took a short break.<br>Дополнительные вопросы не заменяют исходное интервью.');nav();return;}
h.innerHTML='<h3>Домашняя работа · Past</h3><div class="text">1. Повтори два сета 19–24 без ключей. Для ошибок: my answer → correct answer → reason.<br>2. Напиши 6–8 предложений о вчерашнем дне, используй все четыре Past tenses и подчеркни формы.<br>3. Запиши ответ: What did you do last weekend? — 2–3 полных предложения.<br>4. Повтори V2/V3: go, come, take, give, see, write, leave, forget, find, tell, know, begin.</div>';keys(h,'go–went–gone; come–came–come; take–took–taken; give–gave–given; see–saw–seen; write–wrote–written; leave–left–left; forget–forgot–forgotten; find–found–found; tell–told–told; know–knew–known; begin–began–begun.<br><b>Итог:</b> Exit test 5–6/6 — закреплено; 3–4/6 — повторить контрасты; 0–2/6 — вернуться к Simple/Continuous и timeline. Рабочий ориентир для учителя, не экзаменационная шкала.');nav();
}
function gap(h,set,id){h.innerHTML='<h3>'+set.title+'</h3><p class="muted">Прочитай связный текст. Преобразуй слова: исходная форма должна измениться.</p><div class="text"></div><div class="feedback" role="status"></div>';const t=h.querySelector('.text');set.lines.forEach((q,j)=>{const el=document.createElement('span');el.innerHTML=q[0].replace('___','<label><small>'+(19+j)+'</small> <input aria-label="Задание '+(19+j)+' '+q[1]+'" data-save="'+id+'-'+j+'" autocomplete="off" value="'+esc(values[id+'-'+j]||'')+'"> <small>'+q[1]+'</small></label>')+' ';t.append(el);});h.append(button('Проверить',()=>{save();let score=0;t.querySelectorAll('input').forEach((e,j)=>{const ok=set.lines[j][2].some(a=>norm(a)===norm(e.value));e.classList.toggle('ok',ok);e.classList.toggle('bad',!ok);score+=Number(ok);});h.querySelector('.feedback').textContent=score+' / 6. Объясни выбор формы в каждом предложении.';}));keys(h,set.lines.map((q,j)=>'<b>'+(19+j)+'. '+esc(q[2].join(' / '))+'</b> — '+q[3]).join('<br>'));}
})();
