/* Блок «Россия» · задания в формате ФИПИ · авторские тексты, составлены для этого сайта */
window.FIPI_TOPICS=(window.FIPI_TOPICS||[]).concat([
{id:"ru-holidays",group:"Россия",name:"Russia · holidays and traditions",
read:"Maslenitsa is one of the oldest and merriest holidays in Russia. It is celebrated at the end of winter and lasts a whole week. In ancient times people believed that the celebration helped to drive away the cold and to welcome the spring sun. The main dish of the week is blini, thin round pancakes which look like the sun. Families bake them every day and serve them with butter, sour cream, honey or jam. Each day of the week has its own name and customs. People visit their relatives, ride on sledges, sing folk songs and take part in outdoor games. In many towns there are fairs where visitors can buy handmade souvenirs and taste hot tea from a samovar. On the last day, which is called Forgiveness Sunday, people ask each other for forgiveness. In the evening a large straw figure of winter is burnt on a bonfire.",
ads:[
{title:"Maslenitsa festival in the city park!",intro:"You are considering going to the Maslenitsa festival and now you'd like to get more information.",points:["dates of the festival","entrance fee","activities for children","traditional food"],key:["What are the dates of the festival?","How much is the entrance fee?","What activities for children do you have?","What traditional food can I try at the festival?"],pic:"people in a snowy park at a Maslenitsa fair"},
{title:"Folk craft workshop – paint your own matryoshka!",intro:"You are considering taking part in the workshop and now you'd like to get more information.",points:["location","duration of the workshop","price","materials provided"],key:["Where does the workshop take place?","How long does the workshop last?","How much does the workshop cost?","Are materials provided?"],pic:"a table with unpainted wooden dolls, brushes and paints"}],
iv:[
{theme:"Russian holidays",q:["What is your favourite Russian holiday, and why?","How does your family usually celebrate New Year?","What traditional dishes do you cook for holidays?","Which public holiday is celebrated in your town in a special way?","Why is it important to keep national traditions?"]},
{theme:"traditions in Russia",q:["What Russian traditions would you tell a foreign friend about?","What souvenirs do tourists usually bring home from Russia?","How do people in your country welcome guests?","What family traditions do you have?","Do young people still follow old customs? Why or why not?"]}],
ph:[
{project:"Ways of celebrating New Year",kind:"the two ways of celebrating New Year",pref:"which way of celebrating New Year presented in the pictures you'd prefer and why",p1:"a family at a festive table at home next to a decorated tree",p2:"a crowd watching fireworks in a city square at night",adv:"at home: cosy, the whole family together, favourite dishes · in the square: festive atmosphere, fireworks, concerts",dis:"at home: a lot of cooking, nothing new · in the square: cold, crowded, hard to get home"},
{project:"Russian souvenirs",kind:"the two kinds of souvenirs",pref:"which kind of souvenir presented in the pictures you'd prefer to buy and why",p1:"hand-painted matryoshka dolls on a market stall",p2:"fridge magnets with views of a city",adv:"matryoshka: handmade, traditional, a real piece of folk art · magnets: cheap, small, easy to carry",dis:"matryoshka: expensive, takes up space in the luggage · magnets: mass-produced, not very original"}],
mail:{from:"Jack",g:"his",subject:"Holidays in Russia",body:"…We've just celebrated Bonfire Night with a huge fire and fireworks in the park. What is the most popular holiday in your country? How do you celebrate it in your family? What holiday food do you like most of all?\n\nBy the way, my cousin is getting ready for a school exchange trip to Russia…",ask:"his cousin's exchange trip",
sample:"Dear Jack,\n\nThanks for your email. Bonfire Night sounds really exciting!\n\nThe most popular holiday in Russia is New Year. In my family we decorate a fir tree, cook a festive dinner and stay up until midnight to listen to the Kremlin clock and make a wish. Then we give each other presents and go outside to watch the fireworks. Most of all I like Olivier salad, which my mum makes only for this holiday.\n\nIt's great that your cousin is coming to Russia! Which city is he going to stay in? How long will the trip last? Can he speak any Russian?\n\nI have to go now as I need to help my dad.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"which Russian holidays are best known among students in Zetland",col:"Holiday",rows:[["New Year",36],["Maslenitsa",25],["Victory Day",19],["Cosmonautics Day",12],["Russia Day",8]],problem:"learning about the traditions of another country",opinion:"the importance of knowing the holidays and traditions of other countries",hint:"Problem: people get wrong ideas about foreign traditions from films and social networks. Solution: school exchanges, culture festivals, talking to people from that country."},
{subject:"how families in Zetland prefer to celebrate national holidays",col:"Way of celebrating",rows:[["At home with relatives",38],["At public concerts and festivals",24],["Visiting friends",18],["Travelling to another city",12],["Watching celebrations on TV",8]],problem:"celebrating holidays in public places",opinion:"the best way to celebrate a national holiday",hint:"Problem: public places are overcrowded and it is easy to get lost or tired. Solution: plan the route, agree on a meeting point, choose smaller local events."}],
gr:{title:"Cosmonautics Day",items:[
["Cosmonautics Day"," in Russia every year on 12 April.","CELEBRATE",["is celebrated"]],
["On this day in 1961 Yuri Gagarin"," the first person to travel into space.","BECOME",["became"]],
[""," flight around the Earth lasted only 108 minutes.","HE",["his"]],
["Since then hundreds of people"," into space.","FLY",["have flown"]],
["Gagarin's flight was one of the"," events of the twentieth century.","IMPORTANT",["most important"]],
["Even today many"," dream of becoming cosmonauts.","CHILD",["children"]]]},
wf:{title:"New Year in Russia",items:[
["New Year is the most popular"," holiday in Russia.","NATION",["national"]],
["The"," for it start long before 31 December.","PREPARE",["preparations","preparation"]],
["Streets and squares look"," with lights and decorated trees.","WONDER",["wonderful"]],
["Children wait"," for presents from Ded Moroz.","PATIENT",["impatiently","patiently"]],
["At midnight the whole country listens to the Kremlin clock, and the"," usually goes on until morning.","CELEBRATE",["celebration"]]]}
},
{id:"ru-food",group:"Россия",name:"Russia · food and hospitality",
read:"Tea came to Russia from China in the seventeenth century, and at first only rich people could afford it. The journey across Siberia took many months, so the leaves were extremely expensive. Gradually tea became cheaper and turned into the favourite drink of the whole country. Its symbol is the samovar, a large metal container in which water is boiled. The most famous samovars have been made in the city of Tula for more than two hundred years. In the past the whole family gathered around the samovar every evening to share the news of the day. Tea was served with sugar, lemon, honey, jam and different kinds of pastry. Guests were always offered a cup, and refusing it was considered impolite. Although electric kettles have replaced samovars in most homes, the tradition of long conversations over tea is still alive.",
ads:[
{title:"Restaurant of traditional Russian cuisine – taste the real Russia!",intro:"You are considering visiting the restaurant and now you'd like to get more information.",points:["opening hours","vegetarian dishes","average price of a meal","live music"],key:["What are the opening hours of the restaurant?","Do you serve vegetarian dishes?","What is the average price of a meal?","Is there live music in the restaurant?"],pic:"a restaurant table with traditional dishes and a samovar"},
{title:"Cooking class – learn to make pelmeni!",intro:"You are considering taking part in the cooking class and now you'd like to get more information.",points:["date of the class","duration","price","number of participants"],key:["When does the class take place?","How long does the class last?","How much does the class cost?","How many participants are there in the class?"],pic:"hands making small dumplings on a floured table"}],
iv:[
{theme:"Russian food",q:["What traditional Russian dishes do you like?","Which dish does your family cook for special occasions?","What Russian dish would you offer to a foreign guest, and why?","Can you cook any traditional dishes yourself?","Is traditional food still popular with young people in Russia? Why?"]},
{theme:"eating habits in Russia",q:["How often do you eat out?","What kinds of cafes are popular in your town?","Do you prefer Russian food or food from other countries? Why?","What do people in Russia usually drink with their meals?","Why do people like having guests at home?"]}],
ph:[
{project:"Traditional Russian dishes",kind:"the two traditional dishes",pref:"which traditional dish presented in the pictures you'd prefer to offer to a foreign guest and why",p1:"a bowl of borscht with sour cream",p2:"a plate of blini with jam",adv:"borscht: filling, full of vegetables, a real symbol of home cooking · blini: quick to make, many fillings, everyone likes them",dis:"borscht: takes hours to cook, an unusual taste for foreigners · blini: not very healthy, you need practice to make them thin"},
{project:"Ways of having tea",kind:"the two ways of having tea",pref:"which way of having tea presented in the pictures you'd prefer and why",p1:"a family drinking tea from a samovar in the garden",p2:"friends having tea in a modern cafe",adv:"samovar in the garden: tradition, fresh air, the whole family together · cafe: no preparation, many kinds of tea and desserts",dis:"samovar: takes time to prepare, depends on the weather · cafe: costs money, noisy, limited time"}],
mail:{from:"Grace",g:"her",subject:"Russian food",body:"…Our class is having an international food day next week and I've got Russia! What traditional Russian dish is the easiest to cook? What do people in Russia usually have for breakfast? Which Russian dish do you like least, and why?\n\nBy the way, my mum has opened a small bakery…",ask:"her mum's bakery",
sample:"Dear Grace,\n\nThanks for your email. How lucky you are to have got Russia!\n\nI think the easiest traditional dish to cook is blini, thin pancakes made from milk, eggs and flour. For breakfast people in Russia usually have porridge, sandwiches with cheese or syrniki, which are small cottage cheese pancakes. The dish I like least is okroshka because it is a cold soup with kvass and I find its taste rather strange.\n\nCongratulations on your mum's new bakery! What does she bake there? Do you help her at weekends? Where is the bakery located?\n\nI have to go now because my mum is calling me for dinner.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"which Russian dishes people in Zetland would like to try",col:"Dish",rows:[["Pelmeni",33],["Blini",27],["Borscht",21],["Pirozhki",12],["Okroshka",7]],problem:"trying the food of another country",opinion:"whether food helps to understand another culture",hint:"Problem: unfamiliar dishes may seem strange or cause allergies. Solution: read about the ingredients, start with small portions, ask local people for advice."},
{subject:"where people in Zetland prefer to have family dinners on holidays",col:"Place",rows:[["At home",44],["At their relatives' homes",23],["In a restaurant",17],["In a cafe",10],["Outdoors",6]],problem:"cooking a holiday dinner at home",opinion:"the role of family meals in people's lives",hint:"Problem: one person spends the whole day in the kitchen and is too tired to enjoy the holiday. Solution: share the duties – everyone cooks one dish."}],
gr:{title:"Pelmeni",items:[
["Pelmeni are one of the"," dishes of Russian cuisine.","FAMOUS",["most famous"]],
["They"," from thin dough filled with minced meat.","MAKE",["are made"]],
["Last winter my grandmother"," me how to cook them.","TEACH",["taught"]],
["While we"," the dough, she told me stories about her childhood.","PREPARE",["were preparing"]],
["In those days all the"," of the family sat at one table and made hundreds of pelmeni.","WOMAN",["women"]],
["Since then I"," pelmeni for my friends several times.","COOK",["have cooked"]]]},
wf:{title:"Russian hospitality",items:[
["Russia has always been famous for its",".","HOSPITABLE",["hospitality"]],
["A guest is given a warm welcome and a"," meal.","TASTE",["tasty"]],
["The table is"," full of salads, pies and pickles.","USUAL",["usually"]],
["It is simply"," to leave such a table hungry.","POSSIBLE",["impossible"]],
["The"," over a cup of tea can last for hours.","CONVERSE",["conversation"]]]}
},
{id:"ru-people",group:"Россия",name:"Russia · science and famous people",
read:"Mikhail Lomonosov is often called the first great Russian scientist. He was born in 1711 in a fishing village in the north of the country. As a boy he helped his father at sea, but his real passion was reading. At the age of nineteen he left home and walked to Moscow together with a train of carts carrying fish. To enter a school he had to hide the fact that he was a peasant's son. Lomonosov studied brilliantly and was later sent to Germany to continue his education. On returning to Russia he worked in chemistry, physics, astronomy and geography. He also wrote poetry and a grammar of the Russian language. In 1755 he helped to found Moscow University, which now bears his name. The poet Alexander Pushkin once said that Lomonosov himself was our first university.",
ads:[
{title:"Space museum – a journey to the stars!",intro:"You are considering visiting the space museum and now you'd like to get more information.",points:["opening hours","ticket price for students","audio guide in English","taking photos"],key:["What are the opening hours of the museum?","How much is a ticket for students?","Do you have an audio guide in English?","Is it allowed to take photos in the museum?"],pic:"a rocket and a spacesuit in a museum hall"},
{title:"Literary walking tour – in the footsteps of Russian writers",intro:"You are considering going on the literary walking tour and now you'd like to get more information.",points:["starting point","duration of the tour","price","size of the group"],key:["Where does the tour start?","How long does the tour last?","How much does the tour cost?","How many people are there in the group?"],pic:"a guide with a group of tourists near an old house"}],
iv:[
{theme:"famous people of Russia",q:["Which famous Russian person do you admire, and why?","What Russian scientists do you know, and what are they famous for?","Who is your favourite Russian writer?","What Russian book would you recommend to a foreign friend?","Why should people know the history of their country?"]},
{theme:"Russian science and space exploration",q:["What do you know about Yuri Gagarin's flight?","Would you like to fly into space? Why or why not?","What Russian inventions or discoveries do you consider important?","What science museums have you visited?","Is it prestigious to be a scientist nowadays? Why?"]}],
ph:[
{project:"Ways of learning about famous people",kind:"the two ways of learning about famous people",pref:"which way of learning about famous people presented in the pictures you'd prefer and why",p1:"students on an excursion in a writer's house museum",p2:"a girl watching a documentary on a laptop",adv:"museum: real things and atmosphere, a guide answers questions · documentary: at home, free, can be paused and watched again",dis:"museum: tickets and travelling, limited time · documentary: no real objects, easy to get distracted"},
{project:"Russian arts",kind:"the two kinds of art",pref:"which kind of art presented in the pictures you'd prefer to see and why",p1:"a ballet performance on a theatre stage",p2:"visitors looking at paintings in an art gallery",adv:"ballet: music and dance together, strong emotions · gallery: you choose your own pace, you can come back to a picture",dis:"ballet: expensive tickets, hard to understand without knowing the story · gallery: tiring to walk for hours, crowds at famous pictures"}],
mail:{from:"Peter",g:"his",subject:"Russian writers",body:"…We're reading a short story by Chekhov in our literature class and I really like it! Which Russian writers do you study at school? What book have you read recently? Who do you think is the most famous Russian person in the world, and why?\n\nBy the way, I've joined a school theatre club…",ask:"his school theatre club",
sample:"Dear Peter,\n\nThanks for your email. I'm so glad you like Chekhov!\n\nAt school we study Pushkin, Tolstoy, Dostoevsky and, of course, Chekhov. Recently I have read The Captain's Daughter by Pushkin, which is a historical novel about love and honour. I think the most famous Russian person in the world is Yuri Gagarin because he was the first human to fly into space and everybody knows his name.\n\nIt's great that you have joined a theatre club! What play are you rehearsing now? How often do you have rehearsals? What part would you like to play?\n\nI have to go now as I need to finish my essay.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"which famous Russians are best known among students in Zetland",col:"Famous person",rows:[["Yuri Gagarin",34],["Leo Tolstoy",24],["Pyotr Tchaikovsky",19],["Dmitri Mendeleev",14],["Mikhail Lomonosov",9]],problem:"learning about famous people of other countries",opinion:"why it is important to know the famous people of other countries",hint:"Problem: school programmes give little time to foreign history and culture. Solution: project work, documentaries, international quizzes and school exchanges."},
{subject:"what fields of Russian culture people in Zetland are interested in",col:"Field of culture",rows:[["Literature",31],["Ballet",26],["Classical music",20],["Cinema",14],["Painting",9]],problem:"getting to know a foreign culture",opinion:"the role of culture in understanding other nations",hint:"Problem: the language barrier – books and films are hard to understand. Solution: good translations, subtitles, festivals of foreign culture."}],
gr:{title:"Dmitri Mendeleev",items:[
["Dmitri Mendeleev"," in the Siberian town of Tobolsk in 1834.","BEAR",["was born"]],
["He was the"," child in a very large family.","YOUNG",["youngest"]],
["In 1869 he"," the periodic table of chemical elements.","CREATE",["created"]],
["At that time only sixty-three elements"," to scientists.","KNOW",["were known"]],
["Mendeleev left empty places in"," table for the elements that would be discovered later.","HE",["his"]],
["Today the periodic table"," by students all over the world.","USE",["is used"]]]},
wf:{title:"Pyotr Tchaikovsky",items:[
["Pyotr Tchaikovsky is one of the greatest Russian",".","COMPOSE",["composers"]],
["His music is"," all over the world.","FAME",["famous"]],
["His ballets Swan Lake and The Nutcracker are"," performed in many countries.","REGULAR",["regularly"]],
["Surprisingly, the first"," of Swan Lake in 1877 was not a success.","PERFORM",["performance"]],
["Today it is hard to name a more"," ballet.","SUCCESS",["successful"]]]}
},
{id:"ru-places",group:"Россия",name:"Russia · places and nature",
read:"Lake Baikal, which lies in the south of Eastern Siberia, is the deepest lake on the planet. Its greatest depth is more than sixteen hundred metres, and it holds about a fifth of all the fresh water on the surface of the Earth. Scientists believe that the lake is at least twenty-five million years old. More than three hundred rivers flow into Baikal, but only one, the Angara, flows out of it. The water is so clear that in some places you can see the bottom at a depth of forty metres. Thousands of species of plants and animals live in and around the lake, and many of them cannot be found anywhere else. The best known is the Baikal seal, one of the few seals living in fresh water. In winter the lake is covered with thick transparent ice, which attracts photographers and tourists from many countries.",
ads:[
{title:"Golden Ring bus tour – ancient towns of Russia",intro:"You are considering going on the bus tour and now you'd like to get more information.",points:["duration of the tour","number of towns","price per person","meals included"],key:["How long does the tour last?","How many towns will we visit?","How much does the tour cost per person?","Are meals included?"],pic:"a tourist bus near an old white-stone church"},
{title:"Rafting in the Altai mountains – adventure of the summer!",intro:"You are considering going rafting and now you'd like to get more information.",points:["dates","minimum age","equipment provided","level of difficulty"],key:["What are the dates of the trip?","What is the minimum age for participants?","Is equipment provided?","What is the level of difficulty?"],pic:"people in a raft on a mountain river"}],
iv:[
{theme:"travelling around Russia",q:["What places in Russia have you visited?","Which Russian city would you like to see, and why?","What is special about the region where you live?","What would you show a foreign guest in your home town?","Is it better to travel around Russia by train or by plane? Why?"]},
{theme:"the nature of Russia",q:["What is nature like in the place where you live?","What natural wonders of Russia do you know?","Where do people from your town go to enjoy nature?","Would you like to visit Lake Baikal or Kamchatka? Why?","What should be done to protect nature in Russia?"]}],
ph:[
{project:"Tourist destinations in Russia",kind:"the two types of tourist destinations",pref:"which type of tourist destination presented in the pictures you'd prefer to visit and why",p1:"a big city with historical buildings on a river embankment",p2:"a wooden house by a mountain lake",adv:"city: museums, theatres, comfortable hotels, easy to get to · nature: silence, clean air, beautiful views, active rest",dis:"city: crowds, noise, high prices · nature: far away, few facilities, depends on the weather"},
{project:"Ways of seeing a city",kind:"the two ways of seeing a city",pref:"which way of seeing a city presented in the pictures you'd prefer and why",p1:"tourists on a boat trip along a river",p2:"tourists walking along a street with a guide",adv:"boat trip: relaxing, unusual views, you see a lot in a short time · walking tour: details, stories from the guide, you can stop and take photos",dis:"boat trip: you cannot get off, depends on the weather · walking tour: tiring, slow, you see only one district"}],
mail:{from:"Mary",g:"her",subject:"Visiting Russia",body:"…My family is thinking of spending our next holiday in Russia! Which city should we visit first, and why? What is the best season to come? What souvenirs do tourists usually buy in your country?\n\nBy the way, I've started learning Russian…",ask:"her Russian lessons",
sample:"Dear Mary,\n\nThanks for your email. What wonderful news!\n\nI think you should visit Moscow first because it is the capital and you can see the Kremlin, Red Square and lots of museums there. The best season to come is late spring or early summer, when it is warm and the days are long. Tourists usually buy matryoshka dolls, painted wooden spoons and chocolate as souvenirs.\n\nI'm so glad you have started learning Russian! How many lessons a week do you have? Who is your teacher? What do you find the most difficult about the language?\n\nI have to go now because my lesson starts in ten minutes.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"which places in Russia tourists from Zetland would like to visit",col:"Place",rows:[["Moscow",35],["St Petersburg",28],["Lake Baikal",17],["Sochi",12],["Kamchatka",8]],problem:"travelling to a distant country",opinion:"which place a foreign tourist should start with in Russia",hint:"Problem: long distances make a trip expensive and tiring. Solution: plan the route in advance, choose one region for one trip, use night trains."},
{subject:"why people in Zetland would like to visit Russia",col:"Reason",rows:[["To see historical sights",33],["To enjoy nature",25],["To learn about traditions",20],["To try Russian food",13],["To practise the language",9]],problem:"visiting a foreign country",opinion:"what makes a country attractive to tourists",hint:"Problem: the language barrier makes it hard to find the way or ask for help. Solution: learn basic phrases, use a translation app, book a local guide."}],
gr:{title:"St Petersburg",items:[
["St Petersburg"," by Peter the Great in 1703.","FOUND",["was founded"]],
["Today it is the second"," city in Russia.","LARGE",["largest"]],
["The city"," on more than forty islands.","STAND",["stands"]],
["For about two centuries it"," the capital of the Russian Empire.","BE",["was"]],
["Millions of tourists come to see"," palaces, bridges and museums.","IT",["its"]],
["If you come in June, you"," the famous White Nights.","SEE",["will see"]]]},
wf:{title:"The Golden Ring",items:[
["The Golden Ring is a famous"," route to the north-east of Moscow.","TOUR",["tourist"]],
["It includes several ancient towns of great"," importance.","HISTORY",["historical","historic"]],
["Each town has its own",": white-stone churches, monasteries and museums.","ATTRACT",["attractions"]],
["The towns are"," beautiful in winter, when the roofs are covered with snow.","SPECIAL",["especially"]],
["A trip along the Golden Ring is an"," experience.","FORGET",["unforgettable"]]]}
}
]);
/* Задания о России в Открытом банке ФИПИ: только названия и коды, сами задания открываются на сайте ФИПИ */
window.FIPI_BANK=[
["Аудирование · задание 1",["367577"]],
["Аудирование · задание 2",["23BC26","6005D1","275298"]],
["Чтение · задание 11",["Peter and Paul Fortress – 2837D0","Tourism in Kamchatka – DAAC4F","Sights of Sochi – 01CE56","Cathedral of Christ the Saviour – 9A1D5A","Saint Petersburg – 3DC8C7","Russian souvenirs – 7BFCE8","Chinese tea house in Moscow – C5F1E8","City of fountains – AF09F3","State History Museum – B6BB0D","Gorky Park – DD0A09","Aurora – 153F1C","Veliky Novgorod – D69B12","Nevsky Prospect – D2056A","Around Moscow – 6E1269","State Hermitage Museum – 2C5F33","Kazan – DF8333","Polenovo – A51F3B","Letniy Sad – 6FFC8B"]],
["Чтение · задания 12–18",["Challenges for foreigners in Russia – 2B17FC","Life hacks for visiting Russia – 402A1A","B357A0"]],
["Грамматика · задания 19–24",["From the history of Smolensk – 4F8747","An important discovery – 57849C","Beginnings of Russian railways – C1F541","Altai – 53DC7A","Yaroslavl – C0626A","Yakutia – 09574D","Fishing in Kamchatka – 00D9A5"]],
["Словообразование · задания 25–29",["The Altai Mountains – 700D3D","Ferapontov Monastery in Vologda – 7E46A2","Murmansk – 556030"]],
["Письмо · задание 37",["A48C27","F7228B"]]
];
