/* Задания в формате ФИПИ · авторские тексты, составлены для этого сайта */
window.FIPI_TOPICS=(window.FIPI_TOPICS||[]).concat([
{id:"art",name:"Art, fashion and design",
read:"Street art has travelled a long way from the walls of old factories to the halls of famous museums. In the nineteen seventies young people in New York began writing their names on underground trains with spray paint. The city authorities called it a crime and spent millions of dollars cleaning the carriages. Gradually the simple signatures turned into large colourful pictures, and people started to notice the talent behind them. Today many cities invite artists to decorate grey buildings, bridges and school yards. Such paintings can make a dull district brighter and attract tourists, who come to photograph them. Some works carry a serious message about war, poverty or the environment. Others simply make people smile on their way to work. Nevertheless, the argument continues: painting on a wall without permission is still against the law in most countries.",
ads:[
{title:"Modern art gallery – new exhibition opens soon!",intro:"You are considering visiting the exhibition and now you'd like to get more information.",points:["opening date","ticket price","guided tours","souvenir shop"],key:["When does the exhibition open?","How much is a ticket?","Do you have guided tours?","Is there a souvenir shop in the gallery?"],pic:"visitors looking at paintings in a modern gallery"},
{title:"Fashion design workshop for teenagers",intro:"You are considering taking part in the fashion design workshop and now you'd like to get more information.",points:["location","duration of the workshop","materials provided","size of the group"],key:["Where does the workshop take place?","How long does the workshop last?","Are materials provided?","How many people are there in the group?"],pic:"a teenager drawing clothes designs next to a sewing machine"}],
iv:[
{theme:"art",q:["How often do you go to museums or art galleries?","What kind of art do you like most of all?","Can you draw or paint? How well?","Who is your favourite artist, and why?","Should art be taught at school? Why or why not?"]},
{theme:"fashion and clothes",q:["What clothes do you usually wear at school and at home?","Do you follow fashion? Why or why not?","Where do you usually buy your clothes?","What colours do you prefer in clothes?","Is it important to look fashionable? Why?"]}],
ph:[
{project:"Types of art",kind:"the two types of art",pref:"which type of art presented in the pictures you'd prefer to see and why",p1:"an old painting in a museum hall",p2:"a bright graffiti picture on a city wall",adv:"museum painting: history, great masters, calm atmosphere · street art: free, modern, brightens the city",dis:"museum painting: tickets cost money, hard to understand without a guide · street art: may disappear, sometimes spoils buildings"},
{project:"Styles of clothes",kind:"the two styles of clothes",pref:"which style of clothes presented in the pictures you'd prefer to wear and why",p1:"students in school uniform",p2:"teenagers in casual jeans and T-shirts",adv:"uniform: everyone looks equal and neat, no need to choose · casual: comfortable, shows your personality",dis:"uniform: uncomfortable, no individuality · casual: distracts from studies, competition over brands"}],
mail:{from:"Laura",subject:"Art",body:"…Our art teacher took us to a gallery yesterday and I liked it much more than I had expected. How often do you go to museums or exhibitions? What kind of pictures would you hang in your room? Do you think everyone can learn to draw well, and why?\n\nBy the way, I've decided to redecorate my room…",ask:"her plans for redecorating her room",
sample:"Dear Laura,\n\nThanks for your email. I'm glad you enjoyed the gallery!\n\nI go to museums or exhibitions three or four times a year, usually with my class or my parents. In my room I would hang bright pictures of the sea and mountains because they make me feel calm. I think everyone can learn to draw quite well if they practise regularly, although real talent is still rare.\n\nRedecorating your room sounds like fun! What colour are you going to paint the walls? Will you buy any new furniture? Who is going to help you?\n\nI have to go now as I need to tidy up my own room.\n\nKeep in touch.\n\nBest wishes,\nArina"},
pr:[
{subject:"what types of art teenagers in Zetland are interested in",col:"Type of art",rows:[["Music",38],["Cinema",29],["Photography",15],["Painting",11],["Theatre",7]],problem:"getting teenagers interested in art",opinion:"the role of art in teenagers' lives",hint:"Problem: museums and theatres seem boring and expensive to teenagers. Solution: free days for students, interactive exhibitions, school excursions."},
{subject:"what influences the choice of clothes of teenagers in Zetland",col:"Factor",rows:[["Comfort",33],["Friends' opinion",25],["Price",19],["Fashion trends",16],["Parents' advice",7]],problem:"following fashion",opinion:"whether it is important to follow fashion",hint:"Problem: fashionable clothes are expensive and go out of style quickly. Solution: buy a few basic things of good quality and create your own style."}]
},
{id:"entertainment",name:"Entertainment",
read:"Board games are much older than most people imagine. Game boards and pieces have been found in the tombs of Egyptian kings, and chess has been played for about fifteen hundred years. For centuries such games were a favourite evening activity for families and friends. When computers and game consoles appeared, many people thought that board games would soon be forgotten. Surprisingly, the opposite has happened. Sales have been growing every year, and special cafes have opened where visitors can choose from hundreds of games. Players say they are tired of screens and want to spend time face to face. Modern games are very different from the old ones. In some of them players do not compete but work as a team to solve a mystery or save the world. They also train memory, logic and the ability to plan ahead.",
ads:[
{title:"Summer music festival in the city park",intro:"You are considering going to the music festival and now you'd like to get more information.",points:["dates of the festival","ticket price","performers","food and drinks"],key:["What are the dates of the festival?","How much is a ticket?","Who is performing at the festival?","Can I buy food and drinks there?"],pic:"a crowd in front of an open-air stage"},
{title:"Escape room – can you find the way out?",intro:"You are considering visiting the escape room and now you'd like to get more information.",points:["location","number of players","duration of the game","age restrictions"],key:["Where is the escape room located?","How many players can take part in the game?","How long does the game last?","Are there any age restrictions?"],pic:"friends solving a puzzle in an escape room"}],
iv:[
{theme:"cinema and films",q:["How often do you go to the cinema, and who do you go with?","What kinds of films do you like, and why?","What is the best film you have seen recently?","Do you prefer watching films at home or at the cinema? Why?","Would you like to be an actor? Why or why not?"]},
{theme:"music and concerts",q:["What kind of music do you enjoy listening to?","When do you usually listen to music?","Can you play a musical instrument or sing?","Have you ever been to a concert? What was it like?","Why is music important in people's lives?"]}],
ph:[
{project:"Types of entertainment",kind:"the two types of entertainment",pref:"which type of entertainment presented in the pictures you'd prefer and why",p1:"people watching a play at the theatre",p2:"teenagers at an amusement park on a roller coaster",adv:"theatre: culture, live acting, food for thought · amusement park: excitement, fresh air, fun with friends",dis:"theatre: expensive tickets, you must sit still and keep quiet · amusement park: queues, some rides are frightening, depends on the weather"},
{project:"Ways of listening to music",kind:"the two ways of listening to music",pref:"which way of listening to music presented in the pictures you'd prefer and why",p1:"a crowd at a live concert",p2:"a girl listening to music in headphones at home",adv:"concert: live sound, special atmosphere, unforgettable emotions · headphones: any music at any time, free or cheap, nobody disturbs you",dis:"concert: expensive, crowded and loud · headphones: bad for hearing, no shared emotions"}],
mail:{from:"Daniel",subject:"Weekend",body:"…Last weekend my friends and I went to a board game cafe and stayed there for five hours! How do you usually entertain yourself at weekends? What games do you and your friends play? Where do young people in your town go to have fun?\n\nBy the way, I'm going to a rock concert next Friday…",ask:"the rock concert",
sample:"Dear Daniel,\n\nThanks for your email. Five hours in a cafe sounds like a lot of fun!\n\nAt weekends I usually go to the cinema, meet my friends or just watch a series at home. My friends and I often play card games and sometimes we play volleyball in the yard. Young people in my town go to the shopping centre, the skating rink or the park by the river to have fun.\n\nI'm a bit jealous about the rock concert! Which band is going to play? How much did the ticket cost? Who are you going with?\n\nI have to go now because my friends are waiting for me.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what kinds of films are popular among teenagers in Zetland",col:"Kind of film",rows:[["Comedies",30],["Action films",26],["Fantasy",21],["Horror films",14],["Documentaries",9]],problem:"watching films",opinion:"the role of films in teenagers' lives",hint:"Problem: teenagers watch films late at night and some films are too violent. Solution: choose films by age rating and keep a limit on screen time."},
{subject:"how teenagers in Zetland prefer to spend their Saturday evenings",col:"Saturday evening activity",rows:[["Meeting friends",34],["Playing computer games",25],["Watching films at home",20],["Going to the cinema",13],["Reading",8]],problem:"choosing entertainment",opinion:"the best way for teenagers to relax",hint:"Problem: most entertainment is passive and connected with screens. Solution: plan at least one active evening a week – sport, walks, board games."}]
},
{id:"work",name:"Work and household chores",
read:"Not long ago most people chose a profession once and stayed in it until they retired. Today the situation is quite different. Specialists say that young people who are now at school will probably change their career several times. Some jobs are disappearing because machines can do them faster and cheaper, while new ones appear every year. Twenty years ago nobody had heard of app developers or drone operators. That is why employers pay attention not only to a diploma but also to general skills. They look for people who can work in a team, communicate clearly, solve unexpected problems and learn quickly. Such skills are useful in any profession. Part-time jobs and volunteering help teenagers to develop them long before they finish school. Even ordinary household duties teach responsibility and the ability to plan one's time.",
ads:[
{title:"Summer jobs for teenagers at the city park",intro:"You are considering getting a summer job at the city park and now you'd like to get more information.",points:["duties","working hours","salary","minimum age"],key:["What are the duties?","What are the working hours?","What is the salary?","What is the minimum age for the job?"],pic:"teenagers in uniform T-shirts working in a park"},
{title:"Home cleaning service – a clean house in two hours!",intro:"You are considering using the cleaning service and now you'd like to get more information.",points:["price per hour","cleaning products","working days","booking by phone"],key:["How much does the service cost per hour?","What cleaning products do you use?","What days do you work?","Can I book the service by phone?"],pic:"a cleaner with a vacuum cleaner in a living room"}],
iv:[
{theme:"jobs and careers",q:["What job would you like to do in the future, and why?","What jobs are popular with young people in your country?","What is more important in a job: money or interest? Why?","Would you like to work abroad? Why or why not?","What skills do people need to get a good job?"]},
{theme:"household chores",q:["What household chores do you do regularly?","Which chores do you dislike most of all, and why?","How do the members of your family share the housework?","Should children be paid for helping at home? Why or why not?","How do modern devices make housework easier?"]}],
ph:[
{project:"Types of jobs",kind:"the two types of jobs",pref:"which type of job presented in the pictures you'd prefer and why",p1:"a man working at a computer in an office",p2:"a builder working outdoors on a construction site",adv:"office job: comfortable conditions, regular hours · outdoor job: physical activity, fresh air, visible result",dis:"office job: sitting all day, tiring for the eyes · outdoor job: hard and sometimes dangerous, depends on the weather"},
{project:"Ways of working",kind:"the two ways of working",pref:"which way of working presented in the pictures you'd prefer and why",p1:"a woman working on a laptop at home",p2:"colleagues having a meeting in an office",adv:"at home: no travelling, flexible hours, more time with the family · in an office: teamwork, clear border between work and rest",dis:"at home: distractions, loneliness · in an office: time on the road, noise, strict timetable"}],
mail:{from:"Helen",subject:"Housework",body:"…My mum has made a list of chores for everyone in the family, and guess who has to wash the dishes all week! What do you do to help your parents about the house? Which household chores do you find the most boring? Do you think boys and girls should do the same housework, and why?\n\nBy the way, I've found a summer job at a flower shop…",ask:"her summer job",
sample:"Dear Helen,\n\nThanks for your email. Poor you, a whole week of washing up!\n\nTo help my parents, I tidy my room, take out the rubbish and sometimes go shopping for food. I find ironing the most boring chore because it takes ages and you can't do anything else at the same time. I think boys and girls should do the same housework, as everyone will need these skills when they live on their own.\n\nIt's great that you have found a summer job! What will you do at the flower shop? How many days a week will you work? Was it difficult to get this job?\n\nI have to go now as it's my turn to cook dinner.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what jobs teenagers in Zetland would like to do in the future",col:"Job",rows:[["IT specialist",32],["Doctor",23],["Blogger",20],["Engineer",15],["Teacher",10]],problem:"choosing a future job",opinion:"what is the most important thing in choosing a job",hint:"Problem: teenagers choose a job because it is fashionable, without knowing what it involves. Solution: open days, talks with specialists, summer work experience."},
{subject:"what household chores teenagers in Zetland do regularly",col:"Household chore",rows:[["Tidying their room",37],["Washing the dishes",24],["Taking out the rubbish",19],["Shopping for food",13],["Cooking",7]],problem:"doing household chores",opinion:"whether teenagers should help about the house",hint:"Problem: teenagers are busy with school and argue with parents about chores. Solution: a fair family timetable where everyone has clear duties."}]
},
{id:"health",name:"Health and fitness",
read:"Sleep takes up about a third of our lives, yet scientists have only recently begun to understand why we need it so much. While we are asleep, the body repairs its muscles and the brain sorts the information received during the day. Important facts are stored in long-term memory, and useless details are removed. That is why students who sleep well before an exam usually get better results than those who study all night. Doctors recommend that teenagers sleep from eight to ten hours. However, many of them go to bed late because of homework, films and phones. The blue light from screens makes the brain think that it is still daytime, so falling asleep becomes harder. A few simple habits can help: going to bed at the same time, airing the room and putting gadgets away an hour before sleep.",
ads:[
{title:"New fitness club – your first training is free!",intro:"You are considering joining the fitness club and now you'd like to get more information.",points:["location","price of a monthly membership","personal trainer","swimming pool"],key:["Where is the fitness club located?","How much is a monthly membership?","Can I train with a personal trainer?","Is there a swimming pool in the club?"],pic:"people exercising in a modern gym"},
{title:"Yoga classes in the park every morning",intro:"You are considering attending yoga classes and now you'd like to get more information.",points:["starting time","duration of a class","things to bring","classes for beginners"],key:["What time do the classes start?","How long does a class last?","What should I bring to the class?","Do you have classes for beginners?"],pic:"a group of people doing yoga on the grass"}],
iv:[
{theme:"a healthy lifestyle",q:["What do you do to keep fit?","How many hours do you usually sleep?","What healthy habits do the members of your family have?","Do you think teenagers in your country lead a healthy lifestyle? Why?","What bad habits should people give up?"]},
{theme:"health and medicine",q:["What do you do when you catch a cold?","How often do you go to the doctor?","What do you do to relax after a hard day?","Would you like to become a doctor? Why or why not?","How can schools help students to stay healthy?"]}],
ph:[
{project:"Ways of keeping fit",kind:"the two ways of keeping fit",pref:"which way of keeping fit presented in the pictures you'd prefer and why",p1:"people exercising on machines in a gym",p2:"a young man jogging in a park",adv:"gym: modern equipment, a trainer, any weather · jogging: free, fresh air, any time you like",dis:"gym: expensive membership, crowded and stuffy · jogging: depends on the weather, hard to make yourself go"},
{project:"Ways of relaxing",kind:"the two ways of relaxing",pref:"which way of relaxing presented in the pictures you'd prefer and why",p1:"a girl doing yoga at home",p2:"a boy lying on a sofa with a phone",adv:"yoga: good for the body and mind, reduces stress · sofa and phone: no effort, entertaining, you can chat with friends",dis:"yoga: needs effort and regular practice · sofa and phone: no movement, tiring for the eyes, you don't really rest"}],
mail:{from:"Ben",subject:"Keeping fit",body:"…Our PE teacher says that half of our class can't run even one kilometre without stopping! What do you do to keep fit? What do you usually eat for breakfast? What do you think is the unhealthiest habit teenagers have, and why?\n\nBy the way, I've signed up for a city bike race…",ask:"the city bike race",
sample:"Dear Ben,\n\nThanks for your email. I'm afraid my class is not much better at running!\n\nTo keep fit, I go to a dance class twice a week and try to walk to school instead of taking the bus. For breakfast I usually have porridge or an omelette and a cup of tea. I think the unhealthiest habit teenagers have is going to bed very late, because without enough sleep you feel tired and can't concentrate.\n\nGood luck with the city bike race! When does it take place? How long is the route? How are you preparing for it?\n\nI have to go now as my dance class starts soon.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what teenagers in Zetland do to stay healthy",col:"Healthy habit",rows:[["Doing sport",34],["Eating healthy food",23],["Sleeping enough",19],["Walking outdoors",16],["Taking vitamins",8]],problem:"leading a healthy lifestyle",opinion:"the importance of a healthy lifestyle for teenagers",hint:"Problem: lack of time and willpower – healthy habits are quickly given up. Solution: start with small steps and do sport together with friends."},
{subject:"what unhealthy habits are common among teenagers in Zetland",col:"Unhealthy habit",rows:[["Going to bed late",35],["Eating fast food",26],["Spending hours with gadgets",21],["Skipping breakfast",11],["Not doing any sport",7]],problem:"going to bed late",opinion:"how teenagers can change their unhealthy habits",hint:"Problem: lack of sleep leads to tiredness and poor marks. Solution: a fixed bedtime and no gadgets an hour before sleep."}]
}
]);
