/* Задания в формате ФИПИ · авторские тексты, составлены для этого сайта */
window.FIPI_TOPICS=(window.FIPI_TOPICS||[]).concat([
{id:"science",name:"Science and technology",
read:"The first weather satellites were launched more than sixty years ago, and since then they have completely changed our daily lives. Before satellites, forecasters had to rely on reports from ships, balloons and a small number of ground stations. Storms over the ocean often arrived without any warning. Today hundreds of satellites circle the Earth, taking pictures of clouds and measuring the temperature of the sea and the air. Powerful computers turn this information into forecasts for several days ahead. Farmers use them to decide when to plant crops, pilots choose safer routes, and people living on the coast can leave their homes before a hurricane comes. Satellites also help scientists to study how the climate is changing. They show how quickly ice is melting at the poles and how forests are getting smaller in different parts of the world.",
ads:[
{title:"Robotics course for teenagers – build your first robot!",intro:"You are considering joining the robotics course and now you'd like to get more information.",points:["start date","duration of the course","price per month","experience required"],key:["When does the course start?","How long does the course last?","How much does the course cost per month?","Is any experience required?"],pic:"teenagers building a small robot in a classroom"},
{title:"Science museum – touch, try and discover!",intro:"You are considering visiting the science museum and now you'd like to get more information.",points:["opening hours","ticket price","guided tours in English","taking photos"],key:["What are the opening hours of the museum?","How much is a ticket?","Do you have guided tours in English?","Is it allowed to take photos in the museum?"],pic:"visitors trying an experiment in a science museum"}],
iv:[
{theme:"modern technology",q:["What gadgets do you use every day, and what for?","How much time do you spend on the internet a day?","What technology do you use for your studies?","Could you live without your phone for a week? Why or why not?","Which invention has changed people's lives most of all, in your opinion?"]},
{theme:"science",q:["What science subjects do you study at school, and which one do you like best?","Would you like to become a scientist? Why or why not?","What scientific discovery do you consider the most important?","Do you enjoy watching programmes about science? Why?","What problems should scientists solve in the future?"]}],
ph:[
{project:"Ways of reading",kind:"the two ways of reading",pref:"which way of reading presented in the pictures you'd prefer and why",p1:"a girl reading a paper book in an armchair",p2:"a boy reading an e-book on a tablet in the underground",adv:"paper book: pleasant to hold, no battery, better for the eyes · e-book: light, hundreds of books in one device, cheaper",dis:"paper book: heavy, takes up space, costs more · e-book: battery runs out, tiring for the eyes, easy to get distracted"},
{project:"Ways of doing school research",kind:"the two ways of doing school research",pref:"which way of doing school research presented in the pictures you'd prefer and why",p1:"students doing an experiment in a school laboratory",p2:"a student searching for information on a computer",adv:"laboratory: real experience, easy to remember, teamwork · computer: fast, lots of sources, possible at home",dis:"laboratory: needs equipment and a teacher, can be dangerous · computer: unreliable websites, easy to copy without thinking"}],
mail:{from:"Kevin",subject:"Gadgets",body:"…My phone broke yesterday and I suddenly realised how much I depend on it! What do you mostly use your phone for? How do your parents feel about the time you spend online? Which gadget would you like to have in the future, and why?\n\nBy the way, I've just started building my own computer…",ask:"the computer he is building",
sample:"Dear Kevin,\n\nThanks for your email. It was great to hear from you!\n\nI mostly use my phone for chatting with friends, listening to music and looking up information for school. My parents are not happy about the time I spend online and often ask me to put the phone away in the evening. In the future I'd like to have smart glasses because they could translate foreign texts while I am travelling.\n\nIt's amazing that you are building your own computer! Where do you buy the parts? How long will it take you to finish it? What are you going to use it for?\n\nI have to go now as it's time for my English lesson.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what teenagers in Zetland use the internet for",col:"Purpose of using the internet",rows:[["Social networks",36],["Watching videos",27],["Studying",18],["Online games",13],["Shopping",6]],problem:"using the internet",opinion:"the role of the internet in teenagers' lives",hint:"Problem: teenagers spend too much time online and sleep badly. Solution: set a daily limit and switch off gadgets an hour before bed."},
{subject:"which modern inventions people in Zetland consider the most useful",col:"Invention",rows:[["Smartphone",42],["Internet",30],["Washing machine",13],["Car",10],["Television",5]],problem:"using smartphones",opinion:"how technology changes our lives",hint:"Problem: people depend on smartphones and communicate less in real life. Solution: phone-free meals and meetings, more outdoor activities."}]
},
{id:"education",name:"Education and learning",
read:"Many people believe that the best way to learn a language is to move to another country. However, experts say that the place matters less than the method. Successful learners usually have several things in common. First of all, they practise a little every day instead of studying for hours once a week. They are not afraid of making mistakes, because every mistake shows what needs more attention. They also connect the language with their interests: football fans read sports news, while music lovers learn the words of their favourite songs. Speaking is especially important. Even a short conversation helps the brain to remember new words better than silent reading. Modern technology makes practice easier than ever. With a phone you can listen to podcasts on the bus, chat with people abroad and check the pronunciation of any word in seconds.",
ads:[
{title:"Summer language school by the sea",intro:"You are considering studying at the summer language school and now you'd like to get more information.",points:["location","number of lessons a day","accommodation","certificate at the end of the course"],key:["Where is the language school located?","How many lessons a day are there?","What kind of accommodation do you offer?","Will I get a certificate at the end of the course?"],pic:"students in a classroom with a view of the sea"},
{title:"Online maths courses – get ready for your exams!",intro:"You are considering taking an online maths course and now you'd like to get more information.",points:["price of the course","duration of one lesson","number of students in a group","homework"],key:["How much does the course cost?","How long does one lesson last?","How many students are there in a group?","Do students get homework?"],pic:"a teenager studying at a laptop with a notebook"}],
iv:[
{theme:"school life",q:["What subjects are you good at, and which are difficult for you?","What do you like most about your school?","How much time do you spend on your homework every day?","What would you change in your school if you could?","Should students wear a school uniform? Why or why not?"]},
{theme:"learning foreign languages",q:["How long have you been learning English?","What is the most difficult thing for you about learning English?","What do you do to improve your English outside the classroom?","What other language would you like to learn, and why?","Why is it useful to know foreign languages nowadays?"]}],
ph:[
{project:"Ways of studying",kind:"the two ways of studying",pref:"which way of studying presented in the pictures you'd prefer and why",p1:"students sitting in a classroom with a teacher",p2:"a girl having an online lesson at home",adv:"classroom: live contact with the teacher and classmates, discipline · online: no travelling, flexible timetable, lessons can be recorded",dis:"classroom: fixed timetable, time on the road · online: technical problems, harder to concentrate, little communication"},
{project:"Ways of preparing for exams",kind:"the two ways of preparing for exams",pref:"which way of preparing for exams presented in the pictures you'd prefer and why",p1:"a boy studying alone in a library",p2:"a group of friends revising together at a table",adv:"alone: quiet, your own pace, nothing distracts · in a group: you can explain things to each other, more fun",dis:"alone: nobody to ask, easy to get bored · in a group: chatting instead of studying, different levels"}],
mail:{from:"Alice",subject:"School",body:"…We've got a new timetable this term and I now have maths every single day! What subjects do you have most often? What do you usually do during the breaks between lessons? What would you like to change in your school, and why?\n\nBy the way, we went on a school trip to a science centre last week…",ask:"her school trip",
sample:"Dear Alice,\n\nThanks for your email. It's always nice to hear from you!\n\nI have Russian and maths almost every day because we are preparing for the final exams. During the breaks I usually chat with my classmates or have a snack in the canteen. If I could, I would make the first lesson start later, as it is really hard to concentrate at eight in the morning.\n\nYour school trip sounds exciting! What did you see at the science centre? How did you get there? Who did you go with?\n\nI have to go now because I need to revise for a test.\n\nHope to hear from you soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what school subjects are the most popular among teenagers in Zetland",col:"School subject",rows:[["Physical education",29],["Computer science",26],["Foreign languages",21],["History",14],["Maths",10]],problem:"studying difficult subjects at school",opinion:"which school subjects are the most important",hint:"Problem: students fall behind in difficult subjects and lose interest. Solution: ask the teacher for help early, study in small steps, use online lessons."},
{subject:"how teenagers in Zetland learn foreign languages",col:"Way of learning a language",rows:[["Lessons at school",40],["Mobile apps",24],["Films and series",17],["Private tutor",12],["Courses abroad",7]],problem:"learning a foreign language",opinion:"the best way to learn a foreign language",hint:"Problem: little speaking practice, so students are afraid to talk. Solution: speaking clubs, online chats with foreigners, speaking in class every lesson."}]
},
{id:"media",name:"The Media",
read:"Radio was the first medium that could bring news into people's homes at the very moment when events were happening. In the nineteen twenties families gathered around large wooden sets in the evening to listen to concerts, plays and football matches. Many experts expected radio to disappear when television arrived, and later when the internet appeared. However, it has survived every change. Drivers still switch on the radio in their cars, and it remains the most reliable source of information during storms and other emergencies, when other networks stop working. Radio has also found a new life online. Podcasts, which are programmes that can be downloaded and played at any time, attract millions of young listeners. Anyone with a microphone and an idea can start a show, so the choice of topics, from science to comedy, is almost endless.",
ads:[
{title:"School of young journalists – your first article starts here",intro:"You are considering joining the school of young journalists and now you'd like to get more information.",points:["age of students","number of lessons a week","tuition fee","chance to publish articles"],key:["How old are the students of the school?","How many lessons a week are there?","How much is the tuition fee?","Will I have a chance to publish my articles?"],pic:"a teenager with a microphone interviewing a person"},
{title:"Take part in our TV quiz show!",intro:"You are considering taking part in the TV quiz show and now you'd like to get more information.",points:["date of filming","place of filming","prizes","number of people in a team"],key:["When does the filming take place?","Where does the filming take place?","What prizes can we win?","How many people are there in a team?"],pic:"a TV studio with a quiz show stage"}],
iv:[
{theme:"the media",q:["Where do you usually get the news from?","How often do you watch television, and what programmes do you like?","Do you or your family read newspapers or magazines? Which ones?","Can we trust everything we read on the internet? Why or why not?","Would you like to work as a journalist? Why or why not?"]},
{theme:"social networks",q:["What social networks do you use, and what for?","How much time do you spend on social networks every day?","Do you follow any bloggers? What are their blogs about?","What are the dangers of social networks?","Would you like to have your own blog? What would it be about?"]}],
ph:[
{project:"Ways of getting the news",kind:"the two ways of getting the news",pref:"which way of getting the news presented in the pictures you'd prefer and why",p1:"an elderly man reading a newspaper at a table",p2:"a girl reading the news on her smartphone",adv:"newspaper: checked facts, no advertising pop-ups, restful for the eyes · smartphone: the latest news at once, free, videos and photos",dis:"newspaper: news is already old, costs money, paper waste · smartphone: fake news, distracting, tiring for the eyes"},
{project:"Ways of watching films",kind:"the two ways of watching films",pref:"which way of watching films presented in the pictures you'd prefer and why",p1:"a family watching television together on a sofa",p2:"a teenager watching a video on a tablet alone",adv:"TV with the family: shared emotions, big screen · tablet alone: you choose what and when to watch, can pause",dis:"TV: fixed programme, adverts, arguments about what to watch · tablet: small screen, less communication with the family"}],
mail:{from:"Sarah",subject:"TV and internet",body:"…My dad says I spend too much time watching videos instead of reading. What do you usually watch online? How do you learn about what is happening in the world? Do you think newspapers will disappear in the future, and why?\n\nBy the way, I've started my own podcast…",ask:"her podcast",
sample:"Dear Sarah,\n\nThanks for your email. I was really glad to hear from you!\n\nI usually watch travel vlogs and short videos about science online, and sometimes I watch a series in English. I learn about what is happening in the world from news channels on my phone and from my parents. I think paper newspapers will disappear one day because online news is faster and free, though some people will still miss them.\n\nIt's so cool that you have started your own podcast! What is it about? How often do you record new episodes? How many listeners do you have?\n\nI must go now as my favourite show is about to start.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"where people in Zetland get the news from",col:"Source of news",rows:[["Social networks",34],["News websites",28],["Television",22],["Radio",11],["Newspapers",5]],problem:"getting the news from social networks",opinion:"which source of news is the most reliable",hint:"Problem: fake news spreads quickly and people believe it. Solution: check information in several sources and trust official websites."},
{subject:"what types of TV programmes are popular among teenagers in Zetland",col:"Type of programme",rows:[["Series",33],["Music shows",24],["Sports programmes",19],["Quiz shows",15],["News",9]],problem:"watching television",opinion:"the role of television in teenagers' lives",hint:"Problem: many hours in front of the screen leave no time for sport and study. Solution: choose programmes in advance and limit watching to an hour a day."}]
},
{id:"food",name:"Food and drink",
read:"Bread is one of the oldest foods made by humans. Archaeologists have found the remains of flat loaves baked more than ten thousand years ago, long before people began farming. The first bread was simply crushed grain mixed with water and cooked on hot stones. Later the ancient Egyptians discovered that dough left in a warm place grew larger and became soft and light. Since then every culture has created its own varieties. There are long thin loaves in France, dark rye bread in northern Europe and flat round bread baked in clay ovens across Asia. In many languages bread is a symbol of life and friendship. Guests are welcomed with it, and sharing a loaf means trusting each other. Although supermarkets sell bread of every kind, more and more people enjoy baking it at home, filling the kitchen with a wonderful smell.",
ads:[
{title:"Italian cooking classes – from pasta to dessert!",intro:"You are considering taking cooking classes and now you'd like to get more information.",points:["location","duration of one class","price of one class","dishes to cook"],key:["Where do the classes take place?","How long does one class last?","How much does one class cost?","What dishes will we cook?"],pic:"people cooking pasta with a chef in a kitchen"},
{title:"New family cafe in the city centre",intro:"You are considering visiting the new cafe and now you'd like to get more information.",points:["opening hours","vegetarian dishes","booking a table","average price of a meal"],key:["What are the opening hours of the cafe?","Do you serve vegetarian dishes?","Can I book a table in advance?","What is the average price of a meal?"],pic:"a cosy cafe with tables and a menu board"}],
iv:[
{theme:"food and cooking",q:["What do you usually have for breakfast?","What is your favourite dish, and who cooks it?","Can you cook? What dishes can you make?","Do you prefer eating at home or eating out? Why?","What traditional dish of your country would you recommend to a foreigner?"]},
{theme:"healthy eating",q:["What do you eat to stay healthy?","How often do you eat fast food?","What do students usually eat at your school canteen?","Why do many teenagers prefer unhealthy snacks?","What would you change about your eating habits?"]}],
ph:[
{project:"Places to have a meal",kind:"the two places to have a meal",pref:"which place to have a meal presented in the pictures you'd prefer and why",p1:"a family having dinner at home in the kitchen",p2:"friends eating in a fast food restaurant",adv:"at home: healthy, cheap, cosy atmosphere · fast food restaurant: quick, tasty, no washing up",dis:"at home: cooking and cleaning take time · fast food restaurant: unhealthy, costs more, noisy"},
{project:"Ways of getting food",kind:"the two ways of getting food",pref:"which way of getting food presented in the pictures you'd prefer and why",p1:"a woman cooking vegetables at the cooker",p2:"a courier delivering a pizza to the door",adv:"cooking: you know the ingredients, cheaper, a useful skill · delivery: saves time, wide choice, convenient after a hard day",dis:"cooking: takes time and effort, you need to shop · delivery: expensive, food may arrive cold, a lot of packaging"}],
mail:{from:"Mike",subject:"Food",body:"…Yesterday I cooked dinner for the whole family for the first time, and nobody complained! Who usually cooks in your family? What dish would you like to learn to make? What do you usually eat when you meet your friends in town?\n\nBy the way, a new Japanese restaurant has opened near my house…",ask:"the new Japanese restaurant",
sample:"Dear Mike,\n\nThanks for your email. Congratulations on your first family dinner!\n\nIn my family my mum usually cooks, but at weekends my dad makes his special pancakes. I would like to learn to make lasagne because it is my favourite dish and I always order it in cafes. When I meet my friends in town, we usually eat pizza or burgers, although I know it is not very healthy.\n\nI'm curious about the new Japanese restaurant. What dishes do they serve? Is it expensive to eat there? Have you tried eating with chopsticks?\n\nI have to go now because dinner is ready.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what teenagers in Zetland usually eat for lunch at school",col:"School lunch",rows:[["Sandwiches from home",31],["Hot meal in the canteen",27],["Snacks and sweets",22],["Fruit and yoghurt",13],["Nothing",7]],problem:"having lunch at school",opinion:"the importance of healthy food for teenagers",hint:"Problem: many students choose snacks and sweets or skip lunch. Solution: tastier healthy dishes in the canteen and longer lunch breaks."},
{subject:"where people in Zetland prefer to eat out",col:"Place to eat out",rows:[["Fast food restaurants",35],["Cafes",28],["Pizzerias",18],["Traditional restaurants",12],["Street food stalls",7]],problem:"eating out",opinion:"whether it is better to eat out or at home",hint:"Problem: eating out often is expensive and not always healthy. Solution: eat out only on special occasions and choose places with fresh food."}]
}
]);
