/* Задания в формате ФИПИ · авторские тексты, составлены для этого сайта */
window.FIPI_TOPICS=(window.FIPI_TOPICS||[]).concat([
{id:"travelling",name:"Travelling",
read:"Train journeys have a special place in the history of travel. Before planes became common, railways connected distant towns and made long trips possible for ordinary people. Today many travellers are choosing trains again, and not only because tickets can be cheap. A train lets you watch the landscape change slowly, from busy suburbs to quiet fields, forests and mountains. Passengers can walk around, read, work or simply talk to the people sitting next to them. Night trains are especially popular with young people: you fall asleep in one city and wake up in another, saving both time and the cost of a hotel. Trains are also kinder to the environment than cars or planes, as they produce far less pollution per passenger. Of course, delays happen and some routes are slow. Still, for many people the journey itself, not only the destination, is the best part of a holiday.",
ads:[
{title:"Mountain hiking tour – a weekend above the clouds!",intro:"You are considering going on a hiking tour and now you'd like to get more information.",points:["location","duration of the tour","equipment needed","discounts for groups"],key:["Where does the tour take place?","How long does the tour last?","What equipment do I need for the tour?","Are there any discounts for groups?"],pic:"hikers with backpacks on a mountain path"},
{title:"Evening river cruise – see the city from the water!",intro:"You are considering going on a river cruise and now you'd like to get more information.",points:["departure time","price of a ticket","meals on board","online booking"],key:["What time does the cruise depart?","How much does a ticket cost?","Are meals served on board?","Can I book a ticket online?"],pic:"a tourist boat on a river in the evening"}],
iv:[
{theme:"travelling",q:["How often do you and your family travel, and where do you usually go?","What means of transport do you prefer for long journeys, and why?","What things do you always take with you when you go on a trip?","Which place in your country would you recommend to a foreign tourist, and why?","Would you rather travel alone or with friends? Why?"]},
{theme:"holidays",q:["How do you usually spend your summer holidays?","What is the best holiday you have ever had?","Do you prefer active holidays or relaxing on the beach? Why?","What country would you like to visit one day, and why?","Why do you think travelling is so popular nowadays?"]}],
ph:[
{project:"Types of holiday accommodation",kind:"the two types of holiday accommodation",pref:"which type of holiday accommodation presented in the pictures you'd prefer and why",p1:"a family relaxing at a hotel by the swimming pool",p2:"friends camping in tents in a forest",adv:"hotel: comfort, service, no cooking · camping: cheap, close to nature, freedom",dis:"hotel: expensive, crowded, far from nature · camping: depends on the weather, insects, no facilities"},
{project:"Means of travelling",kind:"the two means of travelling",pref:"which means of travelling presented in the pictures you'd prefer and why",p1:"passengers sitting on a plane",p2:"a family travelling by car along a country road",adv:"plane: fast, covers long distances · car: you choose the route, can stop anywhere, cheaper for a family",dis:"plane: expensive tickets, delays, luggage limits · car: tiring for the driver, traffic jams, slow"}],
mail:{from:"Ronny",subject:"Holidays",body:"…Our school year has finally ended and I can't wait to go somewhere! Where do you usually spend your summer holidays? What do you like doing when you find yourself in a new place? Would you rather travel around your own country or go abroad, and why?\n\nBy the way, my parents have just bought a camper van…",ask:"his parents' camper van",
sample:"Dear Ronny,\n\nThanks for your email. It was great to hear from you!\n\nI usually spend my summer holidays at my grandparents' house in the countryside, and in August my family goes to the seaside for two weeks. When I find myself in a new place, I like walking around without a map, trying local food and taking photos. I would rather travel around my own country because it is huge and there are still so many regions I have never seen.\n\nI'm glad your parents have bought a camper van. How many people can sleep in it? Is it difficult to drive? Where are you going to go in it first?\n\nI have to go now as I need to help my mum.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"how teenagers in Zetland prefer to spend their summer holidays",col:"Way of spending holidays",rows:[["At the seaside",38],["Visiting relatives in the countryside",24],["Sightseeing in other cities",19],["At a summer camp",12],["Staying at home",7]],problem:"spending summer holidays away from home",opinion:"the importance of travelling for teenagers",hint:"Problem: a holiday away from home can be too expensive for a family. Solution: plan in advance, book early, choose camps or trips inside the region."},
{subject:"what means of transport people in Zetland prefer for travelling",col:"Means of transport",rows:[["Car",41],["Plane",27],["Train",18],["Bus",9],["Ship",5]],problem:"travelling by car",opinion:"which means of transport is the best for travelling",hint:"Problem: traffic jams and tired drivers make car trips long and dangerous. Solution: plan the route, take breaks every two hours, use trains for long distances."}]
},
{id:"hobbies",name:"Hobbies and sport",
read:"Skateboarding began in California in the nineteen fifties, when surfers wanted something to do on days without waves. They fixed small wheels to wooden boards and rode along empty streets. At first it was seen as a children's game, but the sport quickly developed its own style, music and fashion. Skaters learned to jump over stairs, slide along rails and ride inside empty swimming pools. Many cities banned skating in public places, so special parks were built where young people could practise safely. Today skateboarding is an Olympic sport, and some of its champions are still teenagers. Learning even a simple trick takes weeks of falling and trying again, which teaches patience and courage. Skaters usually help each other and share advice, so beginners feel welcome. All you need is a board, a helmet and a flat piece of ground to start.",
ads:[
{title:"City climbing centre – reach the top!",intro:"You are considering visiting the climbing centre and now you'd like to get more information.",points:["opening hours","price for one visit","lessons for beginners","equipment for rent"],key:["What are the opening hours of the centre?","How much does one visit cost?","Do you have lessons for beginners?","Can I rent the equipment at the centre?"],pic:"a teenager on an indoor climbing wall"},
{title:"Photography club for teenagers",intro:"You are considering joining the photography club and now you'd like to get more information.",points:["location","days of meetings","membership fee","type of camera needed"],key:["Where is the club located?","What days does the club meet?","How much is the membership fee?","What type of camera do I need?"],pic:"teenagers with cameras taking photos in a park"}],
iv:[
{theme:"hobbies",q:["What do you like doing in your free time?","How long have you had your favourite hobby, and how did it start?","Which hobbies are popular with teenagers in your country?","Would you like to turn your hobby into a job? Why or why not?","What new hobby would you like to take up in the future?"]},
{theme:"sport",q:["What sports do you do, and how often?","What sports facilities are there near your home?","Do you prefer watching sport or doing it? Why?","Which sport would you never try, and why?","Why is it important for teenagers to do sport?"]}],
ph:[
{project:"Team and individual sports",kind:"the two kinds of sports",pref:"which kind of sport presented in the pictures you'd prefer and why",p1:"teenagers playing volleyball in a school gym",p2:"a girl running alone in a park",adv:"team: communication, support, team spirit · individual: your own pace, any time, self-discipline",dis:"team: you depend on others, fixed timetable · individual: can be boring, harder to stay motivated"},
{project:"Indoor and outdoor hobbies",kind:"the two kinds of hobbies",pref:"which kind of hobby presented in the pictures you'd prefer and why",p1:"a boy building a model plane at his desk",p2:"two friends fishing by a lake",adv:"indoor: possible in any weather, develops patience · outdoor: fresh air, physical activity, time with friends",dis:"indoor: little movement, tiring for the eyes · outdoor: depends on the weather, needs time and transport"}],
mail:{from:"Emily",subject:"Free time",body:"…I've been so busy with exams lately that I've almost forgotten what free time is! What do you usually do in the evenings after school? How much time do you spend on your hobbies at weekends? Which hobby would you like to take up if you had more time, and why?\n\nBy the way, I've just joined a rowing club…",ask:"her rowing club",
sample:"Dear Emily,\n\nThanks for your email. I'm always glad to hear from you!\n\nIn the evenings after school I usually do my homework first and then read or watch a series. At weekends I spend three or four hours on my hobbies: I draw and go to a dance class. If I had more time, I would take up horse riding because I love animals and it is a great way to be outdoors.\n\nIt's fantastic that you have joined a rowing club! How often do you train? Is it hard to learn to row? Do you take part in any competitions?\n\nI must go now because my dance class starts in half an hour.\n\nKeep in touch.\n\nBest wishes,\nArina"},
pr:[
{subject:"what hobbies are popular among teenagers in Zetland",col:"Hobby",rows:[["Computer games",34],["Sport",26],["Music",17],["Drawing and crafts",14],["Collecting",9]],problem:"having a hobby",opinion:"the role of hobbies in teenagers' lives",hint:"Problem: a hobby can take too much time and hurt school results. Solution: make a weekly timetable and keep hobbies for weekends and free evenings."},
{subject:"why teenagers in Zetland do sport",col:"Reason for doing sport",rows:[["To stay fit and healthy",36],["To spend time with friends",25],["To look good",20],["To win competitions",12],["Because parents insist",7]],problem:"doing sport",opinion:"the importance of sport for teenagers",hint:"Problem: injuries when training without a coach or a warm-up. Solution: train under supervision, warm up, use protective equipment."}]
},
{id:"environment",name:"Weather and environment",
read:"Coral reefs cover less than one per cent of the ocean floor, yet they are home to about a quarter of all sea species. A reef is built by tiny animals called corals, which grow very slowly, sometimes only a few millimetres a year. Bright fish, turtles and thousands of other creatures find food and shelter among them. Reefs also protect coastlines from storms by breaking powerful waves before they reach the shore. Unfortunately, these underwater cities are in danger. When the water becomes too warm, corals lose their colour and may die, a process known as bleaching. Pollution and careless tourism cause further damage. Scientists are now growing young corals in special nurseries and planting them back on damaged reefs. Visitors can help too by never touching corals and by choosing sun cream that does not harm sea life.",
ads:[
{title:"Volunteer day – let's clean our beach together!",intro:"You are considering taking part in the beach clean-up and now you'd like to get more information.",points:["date of the event","meeting place","clothes to wear","tools provided"],key:["When does the event take place?","Where is the meeting place?","What clothes should I wear?","Are tools provided?"],pic:"volunteers collecting litter on a beach"},
{title:"Weather station – excursions for school groups",intro:"You are considering visiting the weather station and now you'd like to get more information.",points:["location","duration of the excursion","price for students","possible days for visits"],key:["Where is the weather station located?","How long does the excursion last?","How much does the excursion cost for students?","What days can we visit the station?"],pic:"a weather station with measuring instruments"}],
iv:[
{theme:"the weather and seasons",q:["What is the weather like in your region in different seasons?","What is your favourite season, and why?","How does the weather influence your mood and plans?","What do you usually do when the weather is bad?","Do you trust weather forecasts? Why or why not?"]},
{theme:"environmental protection",q:["What environmental problems are there in the place where you live?","What do you and your family do to help the environment?","Does your school organise any ecological events? What are they?","Do you think young people care enough about nature? Why?","What can be done to make cities greener?"]}],
ph:[
{project:"Ways of protecting the environment",kind:"the two ways of protecting the environment",pref:"which way of protecting the environment presented in the pictures you'd prefer to take part in and why",p1:"teenagers planting trees in a park",p2:"a girl sorting rubbish into different bins",adv:"planting trees: cleaner air, visible result, teamwork · sorting waste: easy to do every day, saves resources",dis:"planting trees: needs time, tools and care afterwards · sorting waste: needs space at home and special bins nearby"},
{project:"Life in different climates",kind:"living in the two types of climate",pref:"which type of climate presented in the pictures you'd prefer to live in and why",p1:"a snowy northern town in winter",p2:"a hot seaside town with palm trees",adv:"cold: winter sports, beautiful snow, four seasons · hot: lots of sunshine, the sea, fresh fruit all year",dis:"cold: short days, warm clothes, high heating costs · hot: heat is tiring, little rain, tourists everywhere"}],
mail:{from:"Oliver",subject:"Weather",body:"…It has been raining here for a week and everyone in my family is in a bad mood. What is the weather like in your region in autumn? What do you usually do on rainy days? Which season do you like most of all, and why?\n\nBy the way, our class is starting an ecological project next month…",ask:"his class's ecological project",
sample:"Dear Oliver,\n\nThanks for your email. It was nice to get news from you!\n\nIn my region autumn is usually cool and windy, and it often rains in October. On rainy days I stay at home, read books or bake something tasty with my sister. Most of all I like summer because the days are long and warm, so I can spend a lot of time outdoors with my friends.\n\nYour class's ecological project sounds interesting! What is the project about? How long will it last? Will you work in groups or on your own?\n\nI have to go now as I need to walk my dog.\n\nDrop me a line when you can.\n\nBest wishes,\nArina"},
pr:[
{subject:"what environmental problems worry people in Zetland most",col:"Environmental problem",rows:[["Air pollution",35],["Rubbish and waste",27],["Water pollution",18],["Cutting down forests",13],["Noise in cities",7]],problem:"air pollution in cities",opinion:"what everyone can do to protect the environment",hint:"Problem: more cars make the air in cities dangerous for health. Solution: develop public transport and cycle lanes, plant more trees."},
{subject:"what people in Zetland do to help the environment",col:"Eco-friendly habit",rows:[["Saving water and electricity",33],["Sorting rubbish",28],["Using their own bags in shops",21],["Cycling instead of driving",11],["Taking part in clean-ups",7]],problem:"sorting rubbish at home",opinion:"the importance of eco-friendly habits",hint:"Problem: there are not enough recycling bins, so people give up. Solution: local councils should put bins in every yard and explain the rules."}]
},
{id:"money",name:"Money and shopping",
read:"Street markets are among the oldest places of trade in the world. Long before supermarkets appeared, farmers brought vegetables, cheese and honey to the town square and sold them directly to their neighbours. Markets were also places to hear news, meet friends and watch street performers. In many cities this tradition is alive today. Early in the morning sellers put out boxes of fruit, fresh bread and flowers, and by noon the square is full of people. Shoppers can taste food before buying it and ask how it was grown. Prices are sometimes lower than in shops because there is no expensive packaging. Buying from local producers also means that food travels a shorter distance, which is better for the environment. Some markets specialise in second-hand books, clothes or furniture, giving old things a second life.",
ads:[
{title:"New shopping centre – grand opening this month!",intro:"You are considering visiting the shopping centre and now you'd like to get more information.",points:["opening date","number of shops","parking for visitors","special offers on the first day"],key:["When does the shopping centre open?","How many shops are there in the centre?","Is there parking for visitors?","Are there any special offers on the first day?"],pic:"a modern shopping centre building"},
{title:"Online bookshop – thousands of books at your door",intro:"You are considering ordering books from the online shop and now you'd like to get more information.",points:["delivery time","cost of delivery","ways of payment","discounts for regular customers"],key:["How long does delivery take?","How much does delivery cost?","What ways of payment do you accept?","Do you have discounts for regular customers?"],pic:"a stack of books next to a laptop"}],
iv:[
{theme:"shopping",q:["How often do you go shopping, and who do you go with?","What do you enjoy buying most of all?","Do you prefer shopping online or in ordinary shops? Why?","What was the last thing you bought for yourself?","Why do some people dislike shopping?"]},
{theme:"pocket money",q:["Do you get pocket money, and what do you spend it on?","Have you ever saved up for something expensive? What was it?","Should teenagers earn their own money? Why or why not?","What is the best present you have ever bought for someone?","What would you do if you won a lot of money?"]}],
ph:[
{project:"Ways of shopping",kind:"the two ways of shopping",pref:"which way of shopping presented in the pictures you'd prefer and why",p1:"a woman choosing clothes in a shop",p2:"a young man ordering goods on a laptop at home",adv:"in a shop: you can try things on, take them at once · online: saves time, wide choice, easy to compare prices",dis:"in a shop: queues, takes time, smaller choice · online: wrong size or quality, waiting for delivery"},
{project:"Places to buy food",kind:"the two places to buy food",pref:"which place to buy food presented in the pictures you'd prefer and why",p1:"people buying vegetables at a street market",p2:"a family with a trolley in a supermarket",adv:"market: fresh local food, you can talk to the seller · supermarket: everything in one place, open late",dis:"market: open only some days, depends on the weather · supermarket: a lot of packaging, long queues"}],
mail:{from:"Jessica",subject:"Shopping",body:"…My sister and I spent the whole Saturday in the new shopping centre and came home with empty wallets! How often do you go shopping for clothes? Who usually helps you to choose things? What do you think about buying things online?\n\nBy the way, I've started a part-time job at a bakery…",ask:"her part-time job",
sample:"Dear Jessica,\n\nThanks for your email. It was lovely to hear from you!\n\nI go shopping for clothes about once a month, usually before a new season starts. My mum often helps me to choose things because she has good taste, although sometimes I go with my best friend. I think buying things online is convenient and saves time, but you can't try clothes on, so I only order books and gadgets that way.\n\nIt's great that you have started a part-time job! What do you do at the bakery? How many hours a week do you work? What are you going to spend your first salary on?\n\nI'd better go now as I have to finish my homework.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what teenagers in Zetland spend their pocket money on",col:"Things teenagers buy",rows:[["Snacks and fast food",31],["Clothes",24],["Mobile games and apps",20],["Going out with friends",16],["Books",9]],problem:"spending pocket money",opinion:"whether teenagers should get pocket money",hint:"Problem: teenagers spend everything at once and cannot save. Solution: plan a budget, put part of the money aside every week."},
{subject:"where people in Zetland prefer to buy clothes",col:"Place to buy clothes",rows:[["Shopping centres",39],["Online shops",29],["Small local shops",15],["Markets",10],["Second-hand shops",7]],problem:"buying clothes online",opinion:"the best way of shopping for clothes",hint:"Problem: clothes bought online may not fit or look different. Solution: check the size chart and reviews, choose shops with free returns."}]
},
{id:"people",name:"People and society",
read:"For most of history people lived in small communities where everyone knew each other. Neighbours helped to build houses, shared tools and looked after one another's children. In modern cities life is very different. Millions of people live close together, yet many of them have never spoken to the family next door. Researchers say that loneliness is becoming a serious problem, especially among the elderly and the young. That is why new forms of community are appearing. In some districts residents turn empty land into shared gardens where they grow vegetables together. Others organise street parties, book exchanges or repair cafes, where volunteers fix broken things for free. Such projects cost little, but they change the atmosphere of a neighbourhood. People begin to greet each other, feel safer and take better care of the place where they live.",
ads:[
{title:"Volunteers wanted at the animal shelter",intro:"You are considering becoming a volunteer at the animal shelter and now you'd like to get more information.",points:["location","duties of a volunteer","minimum age","working hours"],key:["Where is the animal shelter located?","What are the duties of a volunteer?","What is the minimum age for volunteers?","What are the working hours?"],pic:"a teenager playing with a dog at an animal shelter"},
{title:"International youth camp – make friends from all over the world",intro:"You are considering going to the international youth camp and now you'd like to get more information.",points:["dates","cost of participation","languages spoken","accommodation"],key:["What are the dates of the camp?","How much does participation cost?","What languages are spoken in the camp?","What kind of accommodation do you offer?"],pic:"teenagers from different countries sitting around a campfire"}],
iv:[
{theme:"family",q:["How many people are there in your family, and what are they like?","What do you and your family like doing together?","Who are you closest to in your family, and why?","What household duties do you have?","Is it better to be an only child or to have brothers and sisters? Why?"]},
{theme:"friendship",q:["How did you meet your best friend?","What qualities do you value most in a friend?","How do you and your friends usually spend time together?","Is it possible to have real friends online? Why or why not?","What can spoil a friendship, in your opinion?"]}],
ph:[
{project:"Ways of celebrating a birthday",kind:"the two ways of celebrating a birthday",pref:"which way of celebrating a birthday presented in the pictures you'd prefer and why",p1:"a family having a birthday dinner at home",p2:"teenagers celebrating a birthday in a cafe",adv:"at home: cosy, cheaper, the whole family together · in a cafe: no cooking or cleaning, more fun with friends",dis:"at home: a lot of preparation and washing up · in a cafe: expensive, noisy, limited time"},
{project:"Ways of communicating with friends",kind:"the two ways of communicating with friends",pref:"which way of communicating with friends presented in the pictures you'd prefer and why",p1:"two girls talking on a bench in a park",p2:"a boy having a video call on his phone",adv:"face to face: real emotions, shared activities · online: any distance, any time, quick",dis:"face to face: needs time and a place to meet · online: less personal, depends on the internet, tiring for the eyes"}],
mail:{from:"Tom",subject:"Family",body:"…Last weekend we had a big family reunion and I met cousins I had never seen before! How often do you see your relatives? What do you usually do when the whole family gets together? Who do you take after in your family, and in what way?\n\nBy the way, my elder brother is getting married next month…",ask:"his brother's wedding",
sample:"Dear Tom,\n\nThanks for your email. I was happy to hear from you!\n\nI see my grandparents almost every weekend, but most of my other relatives live far away, so we meet only on big holidays. When the whole family gets together, we cook a big dinner, play board games and look through old photos. Everyone says I take after my dad: we have the same eyes and we are both very stubborn.\n\nWhat exciting news about your brother! Where will the wedding take place? How many guests are invited? What are you going to wear?\n\nI have to go now because my friend is waiting for me.\n\nWrite back soon.\n\nBest wishes,\nArina"},
pr:[
{subject:"what qualities teenagers in Zetland value in their friends",col:"Quality",rows:[["Honesty",37],["Sense of humour",25],["Readiness to help",19],["Similar interests",12],["Popularity",7]],problem:"making friends",opinion:"the role of friendship in teenagers' lives",hint:"Problem: shy teenagers find it hard to make friends and feel lonely. Solution: join a club or a sports team where people share your interests."},
{subject:"how families in Zetland spend their free time together",col:"Family activity",rows:[["Watching films at home",32],["Having meals together",26],["Going for walks",20],["Travelling",14],["Playing board games",8]],problem:"spending time with the family",opinion:"the importance of family time",hint:"Problem: parents work long hours and everyone is busy with gadgets. Solution: agree on one evening a week without phones for a shared activity."}]
}
]);
