(function(){
'use strict';
const base=new URL('./',document.currentScript.src), url=p=>new URL(p,base).href;
const docs={main:{path:'pdf/expert-00.pdf',name:'ЕГЭ Expert · полное пособие',count:185},speaking:{path:'pdf/speaking-tasks.pdf',name:'Устная часть · задания',count:63},vocab:{path:'pdf/vocabulary.pdf',name:'Expert Vocabulary B1–B2 · задания и ключи',count:4},additional:{path:'pdf/additional-materials.pdf',name:'Дополнительные материалы · ЕГЭ / ОГЭ',count:10}};
let data,overlay,topic=0,viewToken=0,pdfTask=null,renderTask=null,zoom=1,currentDoc=null,currentPages=[],currentPage=0,currentTitle='',returnAction=null,resizeTimer;
const cache=new Map();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function button(label,fn,cls){const b=document.createElement('button');b.type='button';b.className=cls||'';b.textContent=label;b.onclick=fn;return b;}
function pause(){if(overlay)overlay.querySelectorAll('audio').forEach(a=>a.pause());}
function shell(title,back){pause();viewToken++;if(renderTask){renderTask.cancel();renderTask=null;}if(!overlay){overlay=document.createElement('section');overlay.className='expert-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Материалы Expert');document.body.appendChild(overlay);}overlay.hidden=false;overlay.innerHTML='';const nav=document.createElement('div');nav.className='expert-nav';nav.append(button('← '+(back?'К теме':'Все темы'),back||close,'expert-backbtn'));const h=document.createElement('h2');h.textContent=title;nav.append(h);nav.append(button('Закрыть',close));overlay.append(nav);document.body.style.overflow='hidden';return overlay;}
function close(){pause();viewToken++;if(renderTask){renderTask.cancel();renderTask=null;}if(overlay){overlay.hidden=true;overlay.innerHTML='';}document.body.style.overflow='';}
async function getData(){if(data)return data;const r=await fetch(url('catalog.json?v=20261003-expert'));if(!r.ok)throw new Error('Не удалось загрузить список материалов.');data=await r.json();return data;}
function fail(target,error){target.innerHTML='';const p=document.createElement('p');p.textContent='Материал не загрузился. '+error.message;target.append(p,button('Повторить',()=>window.openExpert()));}
window.openExpert=async function(){close();document.body.classList.remove('fullWeek');const lp=document.getElementById('lessonPage');if(lp)lp.style.display='none';document.querySelectorAll('.content').forEach(e=>e.classList.remove('on'));const host=document.getElementById('trainerView');host.classList.add('on');host.innerHTML='<div class="expert-shell"><h1>EXPERT · материалы курса</h1><p>Загрузка…</p></div>';document.querySelectorAll('.wbtn,.teacherNav').forEach(e=>e.classList.remove('active'));const side=document.getElementById('side');if(side)side.classList.remove('open');try{await getData();renderHub(host);}catch(e){fail(host,e);}window.scrollTo(0,0);};
function renderHub(host){host.innerHTML='';const box=document.createElement('div');box.className='expert-shell';box.innerHTML='<h1>EXPERT · задания, аудио и ответы</h1><p>13 тем · 26 записей интервью · устная часть · письма · проекты · ответы эксперта</p>';const tools=document.createElement('div');tools.className='expert-tools';Object.entries(docs).forEach(([key,doc])=>tools.append(button(doc.name+' · '+doc.count+' стр.',()=>openPdf(key,Array.from({length:doc.count},(_,i)=>({page:i+1,label:'Страница '+(i+1)})),doc.name,null))));tools.append(button('Образцы проектов 38',()=>openPdf('main',data.samples,'Образцы проектов · задание 38',null)));box.append(tools);const grid=document.createElement('div');grid.className='expert-grid';data.topics.forEach((t,i)=>{const b=button('',()=>openTopic(i),'expert-topic');b.innerHTML='<b>'+String(i+1).padStart(2,'0')+' · '+esc(t.name)+'</b><small>Speaking 1–4 · Writing 37–38<br>2 аудио · скрипты · ответы</small>';grid.append(b);});box.append(grid);const note=document.createElement('p');note.className='expert-footer';note.textContent='Крылова А. С. · материалы присланного пособия. Ответы открываются отдельными кнопками. Нумерация страниц книги и PDF указана в просмотре.';box.append(note);host.append(box);}
function openTopic(i){topic=i;const t=data.topics[i],root=shell(t.name,null),nav=root.querySelector('.expert-nav');nav.insertBefore(button('← Предыдущая тема',()=>openTopic((i+data.topics.length-1)%data.topics.length)),nav.lastChild);nav.insertBefore(button('Следующая тема →',()=>openTopic((i+1)%data.topics.length)),nav.lastChild);const body=document.createElement('div');body.className='expert-body';body.innerHTML='<p class="expert-topicnote">Выберите задание. Каждый материал открывается на весь экран. Для интервью используйте исходную запись; скрипты и модели ответов открывайте после выполнения.</p>';const actions=document.createElement('div');actions.className='expert-actions';const add=(title,sub,fn,key)=>{const b=button('',fn,key?'expert-key':'');b.innerHTML=esc(title)+'<small>'+esc(sub)+'</small>';actions.append(b);};
add('1 · Reading aloud','Текст для чтения вслух',()=>openPdf('speaking',t.reading,t.name+' · Reading aloud',()=>openTopic(i)));
add('2 · Four questions','Два объявления · четыре прямых вопроса',()=>openPdf('speaking',t.questions,t.name+' · Four questions',()=>openTopic(i)));
add('3 · Interview · вариант 1','Пять вопросов · только аудио',()=>openAudio(i,1));
add('3 · Interview · вариант 2','Пять вопросов · только аудио',()=>openAudio(i,2));
add('4 · Photo project','Фотографии и планы двух монологов',()=>openPdf('speaking',t.photos,t.name+' · Photo project',()=>openTopic(i)));
add('37 · Email','Все упражнения на письмо из раздела',()=>openPdf('main',t.email,t.name+' · Email',()=>openTopic(i)));
add('38 · Project','Таблицы, диаграммы и тренировка проекта',()=>openPdf('main',t.project,t.name+' · Project',()=>openTopic(i)));
add('Скрипты интервью','Тексты вопросов из основного пособия',()=>openPdf('main',t.scripts,t.name+' · Скрипты интервью',()=>openTopic(i)),true);
add('Ответы · Speaking','Модели вопросов, интервью и монологов',()=>openPdf('main',t.speakingKeys,t.name+' · Ответы Speaking',()=>openTopic(i)),true);
add('Ответы · Writing','Ключи, образцы писем и проектов',()=>openPdf('main',t.writingKeys,t.name+' · Ответы Writing',()=>openTopic(i)),true);
add('Раздел целиком','Все страницы темы в основном пособии',()=>openPdf('main',t.all,t.name+' · Раздел целиком',()=>openTopic(i)));
body.append(actions);root.append(body);}
function openAudio(i,variant){const t=data.topics[i],n=i*2+variant,root=shell(t.name+' · Interview '+variant,()=>openTopic(i)),body=document.createElement('div');body.className='expert-body';const card=document.createElement('div');card.className='expert-audio';card.innerHTML='<h3>Interview · вариант '+variant+'</h3><p>Answer five questions.<br>Give full answers: 2–3 sentences.<br>You have 40 seconds to answer each question.</p>';const audio=document.createElement('audio');audio.controls=true;audio.preload='metadata';audio.src=url('audio/'+String(n).padStart(2,'0')+'.mp3');audio.setAttribute('aria-label',t.name+' · интервью '+variant);card.append(audio);const error=document.createElement('p');error.hidden=true;error.textContent='Запись не загрузилась. Нажмите «Повторить загрузку».';audio.addEventListener('error',()=>error.hidden=false);card.append(error);const tools=document.createElement('div');tools.className='expert-audiotools';tools.append(button('Сначала',()=>{audio.pause();audio.currentTime=0;}),button('Повторить загрузку',()=>{error.hidden=true;audio.load();}));const label=document.createElement('label');label.textContent='Скорость ';const speed=document.createElement('select');[0.85,1,1.15].forEach(v=>{const option=new Option(v+'×',v,v===1,v===1);speed.add(option);});speed.onchange=()=>audio.playbackRate=Number(speed.value);label.append(speed);tools.append(label);card.append(tools);const keytools=document.createElement('div');keytools.className='expert-audiotools';keytools.append(button('Скрипт',()=>openPdf('main',t.scripts,t.name+' · Скрипты интервью',()=>openAudio(i,variant))),button('Модели ответов',()=>openPdf('main',t.speakingKeys,t.name+' · Ответы Speaking',()=>openAudio(i,variant))));card.append(keytools);body.append(card);root.append(body);}
function pdfLocation(key,page){if(key==='main'){const part=data.mainParts.find(p=>page>=p.start&&page<=p.end);return {path:part.path,page:page-part.start+1};}return {path:docs[key].path,page:page};}
async function loadPdf(key,page){const location=pdfLocation(key,page),cacheKey=location.path;if(cache.has(cacheKey))return cache.get(cacheKey);if(!window.pdfjsLib)throw new Error('Просмотр PDF недоступен. Используйте ссылку PDF.');pdfjsLib.GlobalWorkerOptions.workerSrc=url('vendor/pdf.worker.min.js');const job=pdfjsLib.getDocument({url:url(location.path),isEvalSupported:false,disableAutoFetch:true,disableStream:true,rangeChunkSize:65536});const promise=job.promise;cache.set(cacheKey,promise);try{return await promise;}catch(e){cache.delete(cacheKey);throw e;}}
function openPdf(key,pages,title,back){if(!pages||!pages.length){pages=[{page:1,label:'Полный документ'}];}currentDoc=key;currentPages=pages;currentPage=0;currentTitle=title;returnAction=back;zoom=1;const root=shell(title,back),bar=document.createElement('div');bar.className='expert-pdfbar';bar.append(button('←',()=>movePage(-1)));const select=document.createElement('select');select.id='expertPageSelect';select.setAttribute('aria-label','Страница материала');pages.forEach((p,i)=>select.add(new Option(p.label||('Страница '+p.page),i)));select.onchange=()=>{currentPage=Number(select.value);renderPage();};bar.append(select,button('→',()=>movePage(1)));const count=document.createElement('span');count.id='expertPageCount';bar.append(count);bar.append(button('−',()=>{zoom=Math.max(0.5,zoom-0.25);renderPage();}),button('Вписать',()=>{zoom=1;renderPage();}),button('+',()=>{zoom=Math.min(3,zoom+0.25);renderPage();}));const link=document.createElement('a');const location=pdfLocation(key,pages[0].page);link.href=url(location.path)+'#page='+location.page;link.target='_blank';link.rel='noopener';link.textContent='Открыть PDF';link.id='expertPdfLink';bar.append(link);root.append(bar);const stage=document.createElement('div');stage.className='expert-pdfstage';stage.innerHTML='<canvas id="expertCanvas"></canvas><div class="expert-status" id="expertStatus" role="status">Загрузка страницы…</div>';root.append(stage);renderPage();}
function movePage(delta){currentPage=Math.max(0,Math.min(currentPages.length-1,currentPage+delta));renderPage();}
async function renderPage(){const token=++viewToken;if(renderTask){renderTask.cancel();renderTask=null;}const canvas=document.getElementById('expertCanvas'),status=document.getElementById('expertStatus'),stage=canvas&&canvas.parentElement;if(!canvas)return;const descriptor=currentPages[currentPage],key=currentDoc;document.getElementById('expertPageSelect').value=currentPage;document.getElementById('expertPageCount').textContent=(currentPage+1)+' / '+currentPages.length+' · PDF '+descriptor.page+(key==='main'&&descriptor.page>=3?' · книга '+(descriptor.page+2):'');const location=pdfLocation(key,descriptor.page);document.getElementById('expertPdfLink').href=url(location.path)+'#page='+location.page;status.textContent='Загрузка страницы…';try{const doc=await loadPdf(key,descriptor.page);if(token!==viewToken)return;const page=await doc.getPage(location.page);if(token!==viewToken)return;const natural=page.getViewport({scale:1}),crop=descriptor.crop||[0,1],cropTop=crop[0]*natural.height,cropHeight=(crop[1]-crop[0])*natural.height;const fit=Math.min((stage.clientWidth-20)/natural.width,(stage.clientHeight-20)/cropHeight);const scale=Math.max(0.2,fit)*zoom,dpr=Math.min(window.devicePixelRatio||1,2);const viewport=page.getViewport({scale:scale*dpr});canvas.width=Math.ceil(natural.width*scale*dpr);canvas.height=Math.ceil(cropHeight*scale*dpr);canvas.style.width=Math.ceil(natural.width*scale)+'px';canvas.style.height=Math.ceil(cropHeight*scale)+'px';renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport:viewport,transform:[1,0,0,1,0,-cropTop*scale*dpr]});await renderTask.promise;if(token!==viewToken)return;renderTask=null;status.textContent='';stage.scrollTop=0;}catch(e){if(e.name==='RenderingCancelledException'||token!==viewToken)return;status.textContent='Не удалось открыть страницу. Используйте «Открыть PDF» или повторите переход.';}}
window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(overlay&&!overlay.hidden&&document.getElementById('expertCanvas'))renderPage();},200);});
document.addEventListener('keydown',e=>{if(!overlay||overlay.hidden)return;if(e.key==='Escape')close();if(document.getElementById('expertCanvas')&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName)){if(e.key==='ArrowRight')movePage(1);if(e.key==='ArrowLeft')movePage(-1);}});
})();
